<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYt3o1pb\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYt3o1pb/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerYt3o1pb.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerYt3o1pb\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerYt3o1pb\appProdProjectContainer([
    'container.build_hash' => 'Yt3o1pb',
    'container.build_id' => '1460fe0b',
    'container.build_time' => 1579718621,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYt3o1pb');
