<?php
/**
* 2007-2018 PrestaShop
*
* Jms Mega Menu module for prestashop
*
*  @author    Joommasters <joommasters@gmail.com>
*  @copyright 2007-2018 Joommasters
*  @license   license http://www.gnu.org/licenses/gpl-2.0.html GNU/GPL
*  @Website: http://www.joommasters.com
*/

$query = "DROP TABLE IF EXISTS `_DB_PREFIX_jmsmegamenu`;
CREATE TABLE `_DB_PREFIX_jmsmegamenu` (
  `mitem_id` int(10) UNSIGNED NOT NULL,
  `id_shop` int(11) UNSIGNED NOT NULL,
  `parent_id` int(10) UNSIGNED NOT NULL,
  `type` varchar(30) NOT NULL,
  `value` varchar(255) NOT NULL,
  `html_content` text NOT NULL,
  `active` tinyint(1) NOT NULL,
  `target` varchar(25) NOT NULL,
  `params` text NOT NULL,
  `ordering` int(10) UNSIGNED NOT NULL DEFAULT '0'
) ENGINE=_MYSQL_ENGINE_ DEFAULT CHARSET=utf8;

INSERT INTO `_DB_PREFIX_jmsmegamenu` (`mitem_id`, `id_shop`, `parent_id`, `type`, `value`, `html_content`, `active`, `target`, `params`, `ordering`) VALUES
(84, 1, 0, 'link', '', '', 1, '_self', '{\"class\":\"home\",\"sub\":{\"fullwidth\":\"0\",\"width\":\"\",\"class\":\"sub-home\",\"row\":[[{\"width\":\"12\",\"items\":[{\"item\":\"200\"}]},{\"width\":\"12\",\"items\":[{\"item\":\"202\"}]}],[{\"width\":\"12\",\"items\":[{\"item\":\"204\"}]},{\"width\":\"12\",\"items\":[{\"item\":\"206\"}]},{\"width\":\"12\",\"items\":[{\"item\":\"209\"}]},{\"width\":\"12\",\"items\":[{\"item\":\"212\"}]},{\"width\":\"12\",\"items\":[{\"item\":\"217\"}]},{\"width\":\"12\",\"items\":[{\"item\":\"221\"}]},{\"width\":\"12\",\"items\":[{\"item\":\"225\"}]},{\"width\":\"12\",\"items\":[{\"item\":\"229\"}]}]]}}', 1),
(85, 1, 0, 'category', '10', '', 1, '_self', '{\"class\":\"must-see mega-fullwidth\",\"align\":\"center\",\"sub\":{\"fullwidth\":\"1\",\"width\":\"1120\",\"row\":[[{\"width\":\"3\",\"items\":[{\"item\":\"143\"},{\"item\":\"144\"},{\"item\":\"145\"},{\"item\":\"146\"},{\"item\":\"148\"},{\"item\":\"147\"},{\"item\":\"247\"},{\"item\":\"248\"},{\"item\":\"249\"},{\"item\":\"250\"},{\"item\":\"251\"},{\"item\":\"252\"},{\"item\":\"253\"}]},{\"width\":\"3\",\"items\":[{\"item\":\"151\"},{\"item\":\"152\"},{\"item\":\"153\"},{\"item\":\"154\"},{\"item\":\"155\"},{\"item\":\"156\"},{\"item\":\"157\"},{\"item\":\"158\"}]},{\"width\":\"3\",\"items\":[{\"item\":\"159\"},{\"item\":\"160\"},{\"item\":\"161\"},{\"item\":\"162\"},{\"item\":\"163\"},{\"item\":\"164\"},{\"item\":\"165\"}]},{\"width\":\"3\",\"items\":[{\"item\":\"166\"},{\"item\":\"167\"},{\"item\":\"168\"},{\"item\":\"169\"},{\"item\":\"170\"},{\"item\":\"172\"},{\"item\":\"171\"},{\"item\":\"173\"},{\"item\":\"174\"},{\"item\":\"175\"},{\"item\":\"176\"},{\"item\":\"177\"},{\"item\":\"178\"}]}]]}}', 2),
(86, 1, 0, 'product', '22', '', 1, '_self', '{\"class\":\"mega-fullwidth products\",\"align\":\"center\",\"sub\":{\"fullwidth\":\"1\",\"width\":\"1120\",\"row\":[[{\"width\":\"3\",\"items\":[{\"item\":\"111\"},{\"item\":\"112\"},{\"item\":\"113\"},{\"item\":\"114\"},{\"item\":\"115\"},{\"item\":\"116\"},{\"item\":\"117\"},{\"item\":\"118\"},{\"item\":\"232\"},{\"item\":\"233\"},{\"item\":\"234\"},{\"item\":\"235\"},{\"item\":\"236\"}]},{\"width\":\"3\",\"items\":[{\"item\":\"126\"},{\"item\":\"128\"},{\"item\":\"129\"},{\"item\":\"138\"},{\"item\":\"130\"},{\"item\":\"131\"},{\"item\":\"132\"},{\"item\":\"133\"},{\"item\":\"134\"},{\"item\":\"140\"},{\"item\":\"142\"},{\"item\":\"241\"},{\"item\":\"242\"}]},{\"width\":\"2\",\"items\":[{\"item\":\"127\"},{\"item\":\"119\"},{\"item\":\"246\"},{\"item\":\"245\"},{\"item\":\"120\"},{\"item\":\"121\"},{\"item\":\"122\"},{\"item\":\"123\"},{\"item\":\"124\"},{\"item\":\"125\"},{\"item\":\"137\"},{\"item\":\"139\"},{\"item\":\"141\"}]},{\"width\":\"4\",\"items\":[{\"item\":\"135\"}]}]]}}', 3),
(87, 1, 0, 'category', '10', '', 1, '_self', '{\"sub\":{\"row\":[[{\"width\":\"12\",\"items\":[{\"item\":\"98\"},{\"item\":\"100\"},{\"item\":\"101\"},{\"item\":\"102\"},{\"item\":\"103\"},{\"item\":\"99\"},{\"item\":\"104\"},{\"item\":\"105\"}]}]]}}', 4),
(88, 1, 0, 'jmsblog-singlepost', '2', '', 1, '_self', '{\"sub\":{\"row\":[[{\"width\":\"12\",\"items\":[{\"item\":\"179\"},{\"item\":\"180\"},{\"item\":\"181\"},{\"item\":\"182\"},{\"item\":\"183\"}]}]]}}', 5),
(89, 1, 0, 'link', 'index.php?controller=contact', '', 1, '_self', '{}', 6),
(90, 1, 200, 'link', '', '', 1, '_self', '{\"title\":\"1\"}', 0),
(91, 1, 200, 'link', '', '', 1, '_self', '{\"title\":\"1\"}', 2),
(92, 1, 202, 'link', '', '', 1, '_self', '{\"title\":\"1\"}', 3),
(93, 1, 202, 'link', '', '', 1, '_self', '{\"title\":\"1\"}', 5),
(94, 1, 204, 'link', '', '', 1, '_self', '{\"title\":\"1\"}', 6),
(95, 1, 204, 'link', '', '', 1, '_self', '{\"title\":\"1\"}', 8),
(96, 1, 206, 'link', '', '', 1, '_self', '{\"title\":\"1\"}', 9),
(97, 1, 206, 'link', '', '', 1, '_self', '{\"title\":\"1\"}', 11),
(98, 1, 87, 'cms', '6', '', 1, '_self', '{\"title\":\"1\"}', 1),
(99, 1, 87, 'link', '', '', 1, '_self', '{\"title\":\"1\"}', 2),
(100, 1, 87, 'link', '', '', 1, '_self', '{\"title\":\"1\"}', 3),
(101, 1, 87, 'link', '', '', 1, '_self', '{\"title\":\"1\"}', 4),
(102, 1, 87, 'link', '', '', 1, '_self', '{\"title\":\"1\"}', 5),
(103, 1, 87, 'cms', '4', '', 1, '_self', '{\"title\":\"1\"}', 6),
(104, 1, 87, 'link', '', '', 1, '_self', '{\"title\":\"1\"}', 7),
(105, 1, 87, 'link', 'index.php?controller=404', '', 1, '_self', '{\"title\":\"1\"}', 8),
(111, 1, 86, 'html', 'html_content', '<p><img src=\"themes/jms_storm/assets/img/megamenu_brand_1.jpg\" alt=\"\" /></p>', 1, '_self', '{\"title\":\"0\"}', 0),
(112, 1, 86, 'link', '', '', 1, '_self', '{\"title\":\"1\",\"group\":\"1\"}', 1),
(113, 1, 86, 'link', '', '', 1, '_self', '{\"title\":\"1\"}', 2),
(114, 1, 86, 'link', '', '', 1, '_self', '{\"title\":\"1\"}', 3),
(115, 1, 86, 'link', '', '', 1, '_self', '{\"title\":\"1\"}', 4),
(116, 1, 86, 'link', '', '', 1, '_self', '{\"title\":\"1\"}', 5),
(117, 1, 86, 'link', '', '', 1, '_self', '{\"title\":\"1\"}', 6),
(118, 1, 86, 'link', '', '', 1, '_self', '{\"title\":\"1\"}', 7),
(119, 1, 86, 'link', '#', '', 1, '_self', '{\"title\":\"1\",\"group\":\"1\"}', 9),
(120, 1, 86, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 10),
(121, 1, 86, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 11),
(122, 1, 86, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 12),
(123, 1, 86, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 13),
(124, 1, 86, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 14),
(125, 1, 86, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 15),
(126, 1, 86, 'html', 'html_content', '<p><img src=\"themes/jms_storm/assets/img/megamenu_brand_2.jpg\" alt=\"\" /></p>', 1, '_self', '{\"title\":\"0\"}', 8),
(127, 1, 86, 'html', 'html_content', '<p><img src=\"themes/jms_storm/assets/img/megamenu_brand_3.png\" alt=\"\" /></p>', 1, '_self', '{\"title\":\"0\"}', 16),
(128, 1, 86, 'link', '#', '', 1, '_self', '{\"title\":\"1\",\"group\":\"1\"}', 17),
(129, 1, 86, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 18),
(130, 1, 86, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 19),
(131, 1, 86, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 20),
(132, 1, 86, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 21),
(133, 1, 86, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 22),
(134, 1, 86, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 23),
(135, 1, 86, 'html', 'html_content', '<p><img src=\"themes/jms_storm/assets/img/megamenu_bg_1.jpg\" alt=\"\" /></p>', 1, '_self', '{\"title\":\"0\"}', 24),
(137, 1, 86, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 25),
(138, 1, 86, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 26),
(139, 1, 86, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 27),
(140, 1, 86, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 28),
(141, 1, 86, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 29),
(142, 1, 86, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 30),
(143, 1, 85, 'link', '#', '', 1, '_self', '{\"title\":\"1\",\"group\":\"1\"}', 0),
(144, 1, 85, 'link', '', '', 1, '_self', '{\"title\":\"1\"}', 1),
(145, 1, 85, 'link', '', '', 1, '_self', '{\"title\":\"1\"}', 2),
(146, 1, 85, 'link', '', '', 1, '_self', '{\"title\":\"1\"}', 3),
(147, 1, 85, 'link', '', '', 1, '_self', '{\"title\":\"1\"}', 5),
(148, 1, 85, 'link', '', '', 1, '_self', '{\"title\":\"1\"}', 4),
(151, 1, 85, 'link', '#', '', 1, '_self', '{\"title\":\"1\",\"group\":\"1\"}', 6),
(152, 1, 85, 'product', '23', '', 1, '_self', '{\"title\":\"1\"}', 7),
(153, 1, 85, 'product', '24', '', 1, '_self', '{\"title\":\"1\"}', 8),
(154, 1, 85, 'product', '25', '', 1, '_self', '{\"title\":\"1\"}', 9),
(155, 1, 85, 'product', '22', '', 1, '_self', '{\"title\":\"1\"}', 10),
(156, 1, 85, 'product', '22', '', 1, '_self', '{\"title\":\"1\"}', 11),
(157, 1, 85, 'product', '21', '', 1, '_self', '{\"title\":\"1\"}', 12),
(158, 1, 85, 'product', '27', '', 1, '_self', '{\"title\":\"1\"}', 13),
(159, 1, 85, 'link', '#', '', 1, '_self', '{\"title\":\"1\",\"group\":\"1\"}', 14),
(160, 1, 85, 'link', 'index.php?jpb_addtocart=default', '', 1, '_self', '{\"title\":\"1\"}', 15),
(161, 1, 85, 'link', 'index.php?jpb_addtocart=ajax_popup', '', 1, '_self', '{\"title\":\"1\"}', 16),
(162, 1, 85, 'link', 'index.php?jpb_addtocart=ajax_moveimage', '', 1, '_self', '{\"title\":\"1\"}', 17),
(163, 1, 85, 'link', 'index.php?jpb_addtocart=ajax_cartbottom', '', 1, '_self', '{\"title\":\"1\"}', 18),
(164, 1, 85, 'link', 'index.php?jpb_addtocart=ajax_cartsidebar', '', 1, '_self', '{\"title\":\"1\"}', 19),
(165, 1, 85, 'link', 'index.php?jpb_addtocart=no_ajax', '', 1, '_self', '{\"title\":\"1\"}', 20),
(166, 1, 85, 'link', '#', '', 1, '_self', '{\"title\":\"1\",\"group\":\"1\"}', 21),
(167, 1, 85, 'link', '', '', 1, '_self', '{\"title\":\"1\"}', 22),
(168, 1, 85, 'link', '', '', 1, '_self', '{\"title\":\"1\"}', 23),
(169, 1, 85, 'link', '', '', 1, '_self', '{\"title\":\"1\"}', 24),
(170, 1, 85, 'link', '', '', 1, '_self', '{\"title\":\"1\"}', 25),
(171, 1, 85, 'link', '', '', 1, '_self', '{\"title\":\"1\"}', 26),
(172, 1, 85, 'link', '', '', 1, '_self', '{\"title\":\"1\"}', 27),
(173, 1, 85, 'link', '', '', 1, '_self', '{\"title\":\"1\"}', 28),
(174, 1, 85, 'link', '', '', 1, '_self', '{\"title\":\"1\"}', 29),
(175, 1, 85, 'link', '', '', 1, '_self', '{\"title\":\"1\"}', 30),
(176, 1, 85, 'link', '', '', 1, '_self', '{\"title\":\"1\"}', 31),
(177, 1, 85, 'link', '', '', 1, '_self', '{\"title\":\"1\"}', 32),
(178, 1, 85, 'link', '', '', 1, '_self', '{\"title\":\"1\"}', 33),
(179, 1, 88, 'jmsblog-category', '1', '', 1, '_self', '{\"title\":\"1\"}', 1),
(180, 1, 88, 'jmsblog-singlepost', '3', '', 1, '_self', '{\"title\":\"1\"}', 2),
(181, 1, 88, 'jmsblog-categories', 'jmsblog_categories', '', 1, '_self', '{\"title\":\"1\"}', 3),
(182, 1, 88, 'jmsblog-tag', 'bicycle', '', 1, '_self', '{\"title\":\"1\"}', 4),
(183, 1, 88, 'jmsblog-archive', '2018-10', '', 1, '_self', '{\"title\":\"1\"}', 5),
(184, 1, 179, 'link', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=left', '', 1, '_self', '', 1),
(185, 1, 179, 'link', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=right', '', 1, '_self', '', 2),
(186, 1, 179, 'link', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no', '', 1, '_self', '', 3),
(187, 1, 179, 'link', '', '', 1, '_self', '', 4),
(188, 1, 179, 'link', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no&layout=category-layout-3columns', '', 1, '_self', '', 5),
(189, 1, 179, 'link', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no&layout=category-layout-4columns', '', 1, '_self', '', 6),
(190, 1, 180, 'link', '', '', 1, '_self', '', 1),
(191, 1, 180, 'link', '', '', 1, '_self', '', 2),
(192, 1, 180, 'link', '', '', 1, '_self', '', 3),
(193, 1, 181, 'link', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=left', '', 1, '_self', '', 1),
(194, 1, 181, 'link', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=right', '', 1, '_self', '', 2),
(195, 1, 181, 'link', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=no', '', 1, '_self', '', 3),
(196, 1, 181, 'link', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=left', '', 1, '_self', '', 4),
(197, 1, 181, 'link', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=no&layout=categories-layout-3columns', '', 1, '_self', '', 5),
(198, 1, 181, 'link', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=no&layout=categories-layout-4columns', '', 1, '_self', '', 6),
(200, 1, 84, 'link', '', '<p><a href=\"index.php?settingpanel=1&jpb_homepage=2\"> <img src=\"themes/jms_storm/assets/img/skins/2.jpg\" /> </a></p>', 1, '_self', '{\"title\":\"1\"}', 1),
(202, 1, 84, 'link', '', '<p><a href=\"index.php?settingpanel=1&jpb_homepage=4\"> <img src=\"themes/jms_storm/assets/img/skins/4.jpg\" /> </a></p>', 1, '_self', '{\"title\":\"1\"}', 4),
(204, 1, 84, 'link', '', '<p><a href=\"index.php?settingpanel=1&jpb_homepage=6\"> <img src=\"themes/jms_storm/assets/img/skins/6.jpg\" /> </a></p>', 1, '_self', '{\"title\":\"1\"}', 7),
(206, 1, 84, 'link', '', '<p><a href=\"index.php?settingpanel=1&jpb_homepage=8\"> <img src=\"themes/jms_storm/assets/img/skins/8.jpg\" /> </a></p>', 1, '_self', '{\"title\":\"1\"}', 10),
(207, 1, 209, 'link', '', '', 1, '_self', '{\"title\":\"1\"}', 12),
(209, 1, 84, 'link', '', '<p><a href=\"index.php?settingpanel=1&jpb_homepage=10\"> <img src=\"themes/jms_storm/assets/img/skins/10.jpg\" /> </a></p>', 1, '_self', '{\"title\":\"1\"}', 13),
(210, 1, 209, 'link', '', '', 1, '_self', '{\"title\":\"1\"}', 14),
(212, 1, 84, 'link', '', '<p><a href=\"index.php?settingpanel=1&jpb_homepage=12\"> <img src=\"themes/jms_storm/assets/img/skins/12.jpg\" /> </a></p>', 1, '_self', '{\"title\":\"1\"}', 16),
(213, 1, 212, 'link', '', '', 1, '_self', '{\"title\":\"1\"}', 15),
(214, 1, 212, 'link', '', '', 1, '_self', '{\"title\":\"1\"}', 17),
(216, 1, 217, 'link', '', '<p><a href=\"index.php?settingpanel=1&jpb_homepage=13\"> <img src=\"themes/jms_storm/assets/img/skins/13.jpg\" /> </a></p>', 1, '_self', '{\"title\":\"1\"}', 18),
(217, 1, 84, 'link', '', '<p><a href=\"index.php?settingpanel=1&jpb_homepage=14\"> <img src=\"themes/jms_storm/assets/img/skins/14.jpg\" /> </a></p>', 1, '_self', '{\"title\":\"1\"}', 19),
(218, 1, 217, 'link', '', '', 1, '_self', '{\"title\":\"1\"}', 20),
(220, 1, 221, 'link', '', '', 1, '_self', '{\"title\":\"1\"}', 21),
(221, 1, 84, 'link', '', '<p><a href=\"index.php?settingpanel=1&jpb_homepage=16\"> <img src=\"themes/jms_storm/assets/img/skins/16.jpg\" /> </a></p>', 1, '_self', '{\"title\":\"1\"}', 22),
(224, 1, 225, 'link', '', '', 1, '_self', '{\"title\":\"1\"}', 24),
(225, 1, 84, 'link', '', '<p><a href=\"index.php?settingpanel=1&jpb_homepage=18\"> <img src=\"themes/jms_storm/assets/img/skins/18.jpg\" /> </a></p>', 1, '_self', '{\"title\":\"1\"}', 25),
(226, 1, 225, 'link', '', '', 1, '_self', '{\"title\":\"1\"}', 26),
(228, 1, 229, 'link', '', '', 1, '_self', '{\"title\":\"1\"}', 27),
(229, 1, 84, 'link', '', '<p><a href=\"index.php?settingpanel=1&jpb_homepage=20\"> <img src=\"themes/jms_storm/assets/img/skins/20.jpg\" /> </a></p>', 1, '_self', '{\"title\":\"1\"}', 28),
(230, 1, 229, 'link', '', '', 1, '_self', '{\"title\":\"1\"}', 29),
(231, 1, 221, 'link', '', '', 1, '_self', '{\"title\":\"1\"}', 23),
(232, 1, 86, 'product', '', '', 1, '_self', '{\"title\":\"1\"}', 7),
(233, 1, 86, 'product', '', '', 1, '_self', '{\"title\":\"1\"}', 31),
(234, 1, 86, 'product', '', '', 1, '_self', '{\"title\":\"1\"}', 32),
(235, 1, 86, 'product', '', '', 1, '_self', '{\"title\":\"1\"}', 33),
(236, 1, 86, 'product', '', '', 1, '_self', '{\"title\":\"1\"}', 34),
(241, 1, 86, 'product', '', '', 1, '_self', '{\"title\":\"1\"}', 35),
(242, 1, 86, 'product', '', '', 1, '_self', '{\"title\":\"1\"}', 36),
(245, 1, 86, 'product', '', '', 1, '_self', '{\"title\":\"1\"}', 7),
(246, 1, 86, 'product', '', '', 1, '_self', '{\"title\":\"1\"}', 8),
(247, 1, 85, 'link', '', '', 1, '_self', '{\"title\":\"1\",\"group\":\"1\"}', 34),
(248, 1, 85, 'link', '', '', 1, '_self', '{\"title\":\"1\"}', 35),
(249, 1, 85, 'link', '', '', 1, '_self', '{\"title\":\"1\"}', 36),
(250, 1, 85, 'link', '', '', 1, '_self', '{\"title\":\"1\"}', 37),
(251, 1, 85, 'link', '', '', 1, '_self', '{\"title\":\"1\"}', 38),
(252, 1, 85, 'link', '', '', 1, '_self', '{\"title\":\"1\"}', 39),
(253, 1, 85, 'link', '', '', 1, '_self', '{\"title\":\"1\"}', 40);

DROP TABLE IF EXISTS `_DB_PREFIX_jmsmegamenu_lang`;
CREATE TABLE `_DB_PREFIX_jmsmegamenu_lang` (
  `mitem_id` int(11) NOT NULL,
  `id_lang` int(11) NOT NULL,
  `name` varchar(50) NOT NULL,
  `menulink` varchar(255) NOT NULL
) ENGINE=_MYSQL_ENGINE_ DEFAULT CHARSET=utf8;

INSERT INTO `_DB_PREFIX_jmsmegamenu_lang` (`mitem_id`, `id_lang`, `name`, `menulink`) VALUES
(84, 1, 'Home', 'index.php'),
(85, 1, 'Shop', ''),
(86, 1, 'Products', ''),
(87, 1, 'Pages', ''),
(88, 1, 'Blog', ''),
(89, 1, 'Contact', 'index.php?controller=contact'),
(90, 1, 'Bicycle Home V.1', 'index.php?settingpanel=1&jpb_homepage=1'),
(91, 1, 'Bicycle Home V.2', 'index.php?settingpanel=1&jpb_homepage=2'),
(92, 1, 'Digital Home V.1', 'index.php?settingpanel=1&jpb_homepage=3'),
(93, 1, 'Digital Home V.2', 'index.php?settingpanel=1&jpb_homepage=4'),
(94, 1, 'Fashion Home V.1', 'index.php?settingpanel=1&jpb_homepage=5'),
(95, 1, 'Fashion Home V.2', 'index.php?settingpanel=1&jpb_homepage=6'),
(96, 1, 'Food  Home V.1', 'index.php?settingpanel=1&jpb_homepage=7'),
(97, 1, 'Food  Home V.2', 'index.php?settingpanel=1&jpb_homepage=8'),
(98, 1, 'Typography', ''),
(99, 1, 'Wishlist Page', 'index.php?fc=module&module=jmswishlist&controller=mywishlist&id_lang=1'),
(100, 1, 'Our Store', 'index.php?controller=stores'),
(101, 1, 'Search Page', 'index.php?controller=search&search_query=gop'),
(102, 1, 'Site Map', 'index.php?controller=sitemap'),
(103, 1, 'About Us', 'index.php?controller=new-products'),
(104, 1, 'Best Sales', 'index.php?controller=best-sales'),
(105, 1, '404 Page', 'index.php?controller=404'),
(111, 1, 'LG Image', ''),
(112, 1, 'audio & television', '#'),
(113, 1, '3D glasses', '#'),
(114, 1, 'virtual reality headsets', '#'),
(115, 1, 'PC Accessories', '#'),
(116, 1, 'Video Glasses', '#'),
(117, 1, 'PC game headsets', '#'),
(118, 1, 'video game VR headsets', '#'),
(119, 1, 'Accessories', '#'),
(120, 1, 'Shoes & Bags', '#'),
(121, 1, 'Sunglasses', '#'),
(122, 1, 'Watches & Jewelry', '#'),
(123, 1, 'Scarves & Gloves', '#'),
(124, 1, 'Hats & Ties', '#'),
(125, 1, 'Belts', '#'),
(126, 1, 'Sony Image', ''),
(127, 1, 'Samsung Image', ''),
(128, 1, 'Men', '#'),
(129, 1, 'Blazers', '#'),
(130, 1, 'Trousers', '#'),
(131, 1, 'T-Shirts', '#'),
(132, 1, 'Polo-Shirts', '#'),
(133, 1, 'Short', '#'),
(134, 1, 'Jeans', '#'),
(135, 1, 'Discount Image', ''),
(137, 1, 'Polo-Shirts', '#'),
(138, 1, 'Jeans', '#'),
(139, 1, 'Dresess', '#'),
(140, 1, 'Shorts', '#'),
(141, 1, 'Trousers', '#'),
(142, 1, 'Sweatshirts', '#'),
(85, 8, 'Shop', ''),
(89, 8, 'Contact', 'index.php?controller=contact'),
(98, 8, 'Typography', ''),
(105, 8, '404 Page', 'index.php?controller=404'),
(101, 8, 'Search Page', 'index.php?controller=search&search_query=adiva'),
(102, 8, 'Compare page', 'index.php?controller=products-comparison'),
(90, 8, 'Home 1', 'index.php?settingpanel=1&jpb_homepage=6'),
(91, 8, 'Home 2', 'index.php?settingpanel=1&jpb_homepage=6'),
(92, 8, 'Home 3', 'index.php?settingpanel=1&jpb_homepage=7'),
(93, 8, 'Home 4', 'index.php?settingpanel=1&jpb_homepage=8'),
(94, 8, 'Home 5', 'index.php?settingpanel=1&jpb_homepage=9'),
(95, 8, 'Home 6', 'index.php?settingpanel=1&jpb_homepage=10'),
(96, 8, 'Home 7', 'index.php?settingpanel=1&jpb_homepage=11'),
(97, 8, 'Home 8', 'index.php?settingpanel=1&jpb_homepage=12'),
(111, 8, 'Women Image', ''),
(126, 8, 'Accessories Image', ''),
(127, 8, 'Men Image', ''),
(135, 8, 'Discount Image', ''),
(111, 6, 'Women Image', ''),
(126, 6, 'Accessories Image', ''),
(127, 6, 'Men Image', ''),
(135, 6, 'Discount Image', ''),
(85, 6, 'Shop', ''),
(88, 6, 'Blog', ''),
(88, 8, 'Blog', ''),
(143, 1, 'Product Layout', '#'),
(143, 6, 'Product Layout', '#'),
(143, 8, 'Product Layout', '#'),
(144, 1, 'Left sidebar', 'index.php?id_product=22&id_product_attribute=57&rewrite=hp-lp3065&controller=product&id_lang=1&sidebar=left'),
(144, 6, 'Left sidebar', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=left'),
(144, 8, 'Left sidebar', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=left'),
(145, 1, 'Right sidebar', 'index.php?id_product=22&id_product_attribute=57&rewrite=hp-lp3065&controller=product&id_lang=1&sidebar=right'),
(145, 6, 'Right sidebar', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=right'),
(145, 8, 'Right sidebar', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=right'),
(146, 1, 'No Sidebar', 'index.php?id_product=22&id_product_attribute=57&rewrite=hp-lp3065&controller=product&id_lang=1&sidebar=no'),
(146, 6, 'No Sidebar', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=no'),
(146, 8, 'No Sidebar', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=no'),
(147, 1, '3 Columns Layout', 'index.php?id_product=22&id_product_attribute=57&rewrite=hp-lp3065&controller=product&id_lang=1&sidebar=no&layout=product-layout-3columns'),
(147, 6, '3 Columns Layout', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=no&layout=product-layout-3columns'),
(147, 8, '3 Columns Layout', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=no&layout=product-layout-3columns'),
(148, 1, '2 Columns Layout', 'index.php?id_product=22&id_product_attribute=57&rewrite=hp-lp3065&controller=product&id_lang=1&sidebar=left'),
(148, 6, 'Gallery Layout', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=no&layout=product-layout-gallery'),
(148, 8, 'Gallery Layout', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=no&layout=product-layout-gallery'),
(151, 1, 'Product Type', '#'),
(151, 6, 'Product Type', '#'),
(151, 8, 'Product Type', '#'),
(152, 1, 'Virtual Product', ''),
(152, 6, 'Virtual Product', ''),
(152, 8, 'Virtual Product', ''),
(153, 1, 'Standard Product', ''),
(153, 6, 'Standard Product', ''),
(153, 8, 'Standard Product', ''),
(154, 1, 'Pack Products', ''),
(154, 6, 'Pack Products', ''),
(154, 8, 'Pack Products', ''),
(155, 1, 'Product Color Swatch', ''),
(155, 6, 'Product Color Swatch', ''),
(155, 8, 'Product Color Swatch', ''),
(156, 1, 'Product with custom tab', ''),
(156, 6, 'Product with custom tab', ''),
(156, 8, 'Product with custom tab', ''),
(157, 1, 'Product with video', ''),
(157, 6, 'Product with video', ''),
(157, 8, 'Product with video', ''),
(158, 1, 'Product out of stock', ''),
(158, 6, 'Product out of stock', ''),
(158, 8, 'Product out of stock', ''),
(159, 1, 'Add to cart', '#'),
(159, 6, 'Add to cart', '#'),
(159, 8, 'Add to cart', '#'),
(160, 1, 'Ajax Default', 'index.php?jpb_addtocart=default'),
(160, 6, 'Ajax Default', 'index.php?jpb_addtocart=default'),
(160, 8, 'Ajax Default', 'index.php?jpb_addtocart=default'),
(161, 1, 'Ajax + Preview Popup', 'index.php?jpb_addtocart=ajax_popup'),
(161, 6, 'Ajax + Preview Popup', 'index.php?jpb_addtocart=ajax_popup'),
(161, 8, 'Ajax + Preview Popup', 'index.php?jpb_addtocart=ajax_popup'),
(162, 1, 'Ajax + Image Moving', 'index.php?jpb_addtocart=ajax_moveimage'),
(162, 6, 'Ajax + Image Moving', 'index.php?jpb_addtocart=ajax_moveimage'),
(162, 8, 'Ajax + Image Moving', 'index.php?jpb_addtocart=ajax_moveimage'),
(163, 1, 'Ajax + Cart at Bottom', 'index.php?jpb_addtocart=ajax_cartbottom'),
(163, 6, 'Ajax + Cart at Bottom', 'index.php?jpb_addtocart=ajax_cartbottom'),
(163, 8, 'Ajax + Cart at Bottom', 'index.php?jpb_addtocart=ajax_cartbottom'),
(164, 1, 'Ajax + Cart at Sidebar', 'index.php?jpb_addtocart=ajax_cartsidebar'),
(164, 6, 'Ajax + Cart at Sidebar', 'index.php?jpb_addtocart=ajax_cartsidebar'),
(164, 8, 'Ajax + Cart at Sidebar', 'index.php?jpb_addtocart=ajax_cartsidebar'),
(165, 1, 'No Ajax', 'index.php?jpb_addtocart=no_ajax'),
(165, 6, 'No Ajax', 'index.php?jpb_addtocart=no_ajax'),
(165, 8, 'No Ajax', 'index.php?jpb_addtocart=no_ajax'),
(166, 1, 'Category Layout', '#'),
(166, 6, 'Category Layout', '#'),
(166, 8, 'Category Layout', '#'),
(167, 1, 'Left sidebar', 'index.php?id_category=10&controller=category&id_lang=1&sidebar=left'),
(167, 6, 'Left sidebar', 'index.php?id_category=40&controller=category&id_lang=1&sidebar=left'),
(167, 8, 'Left sidebar', 'index.php?id_category=40&controller=category&id_lang=1&sidebar=left'),
(168, 1, 'Right sidebar', 'index.php?id_category=10&controller=category&id_lang=1&sidebar=right'),
(168, 6, 'Right sidebar', 'index.php?id_category=40&controller=category&id_lang=1&sidebar=right'),
(168, 8, 'Right sidebar', 'index.php?id_category=40&controller=category&id_lang=1&sidebar=right'),
(169, 1, 'No Sidebar', 'index.php?id_category=10&controller=category&id_lang=1&sidebar=no'),
(169, 6, 'No Sidebar', 'index.php?id_category=40&controller=category&id_lang=1&sidebar=no'),
(169, 8, 'No Sidebar', 'index.php?id_category=40&controller=category&id_lang=1&sidebar=no'),
(170, 1, 'Category Banner', 'index.php?id_category=112&controller=category&id_lang=1&sidebar=left&layout=category-layout-banner'),
(170, 6, 'Category Banner', 'index.php?id_category=46&controller=category&id_lang=1&sidebar=left&layout=category-layout-banner'),
(170, 8, 'Category Banner', 'index.php?id_category=46&controller=category&id_lang=1&sidebar=left&layout=category-layout-banner'),
(171, 1, ' Banner and Descriptions', 'index.php?id_category=112&controller=category&id_lang=1&sidebar=left&layout=category-layout-bannerandesc'),
(171, 6, 'Sub Categories', 'index.php?id_category=46&controller=category&id_lang=1&sidebar=left&layout=category-layout-bannerandesc'),
(171, 8, 'Sub Categories', 'index.php?id_category=46&controller=category&id_lang=1&sidebar=left&layout=category-layout-bannerandesc'),
(172, 1, 'Category Descriptions', 'index.php?id_category=112&controller=category&id_lang=1&sidebar=left&layout=category-layout-desc'),
(172, 6, 'Category Descriptions', 'index.php?id_category=46&controller=category&id_lang=1&sidebar=left&layout=category-layout-desc'),
(172, 8, 'Category Descriptions', 'index.php?id_category=46&controller=category&id_lang=1&sidebar=left&layout=category-layout-desc'),
(173, 1, 'Grid 2 Colums', 'index.php?id_category=10&controller=category&id_lang=1&ppr=2'),
(173, 6, 'Grid 2 Colums', 'index.php?id_category=46&controller=category&id_lang=1&ppr=2'),
(173, 8, 'Grid 2 Colums', 'index.php?id_category=46&controller=category&id_lang=1&ppr=2'),
(174, 1, 'Grid 3 Colums', 'index.php?id_category=10&controller=category&id_lang=1&ppr=3'),
(174, 6, 'Grid 3 Colums', 'index.php?id_category=46&controller=category&id_lang=1&ppr=3'),
(174, 8, 'Grid 3 Colums', 'index.php?id_category=46&controller=category&id_lang=1&ppr=3'),
(175, 1, 'Grid 4 Colums', 'index.php?id_category=10&controller=category&id_lang=1&ppr=4'),
(175, 6, 'Grid 4 Colums', 'index.php?id_category=46&controller=category&id_lang=1&ppr=4'),
(175, 8, 'Grid 4 Colums', 'index.php?id_category=46&controller=category&id_lang=1&ppr=4'),
(176, 1, 'Grid 5 Colums', 'index.php?id_category=10&controller=category&id_lang=1&sidebar=no&ppr=5'),
(176, 6, 'Grid 5 Colums', 'index.php?id_category=46&controller=category&id_lang=1&sidebar=no&ppr=5'),
(176, 8, 'Grid 5 Colums', 'index.php?id_category=46&controller=category&id_lang=1&sidebar=no&ppr=5'),
(177, 1, 'Grid 6 Colums', 'index.php?id_category=10&controller=category&id_lang=1&sidebar=no&ppr=6'),
(177, 6, 'Grid 6 Colums', 'index.php?id_category=46&controller=category&id_lang=1&sidebar=no&ppr=6'),
(177, 8, 'Grid 6 Colums', 'index.php?id_category=46&controller=category&id_lang=1&sidebar=no&ppr=6'),
(178, 1, 'List Layout', 'index.php?id_category=10&controller=category&id_lang=1&jpb_grid=0&sidebar=left'),
(178, 6, 'List Layout', '#'),
(178, 8, 'List Layout', '#'),
(179, 1, 'Blog Category', ''),
(179, 6, 'Blog Category', ''),
(179, 8, 'Blog Category', ''),
(180, 1, 'Blog single post', ''),
(180, 6, 'Blog single post', ''),
(180, 8, 'Blog single post', ''),
(181, 1, 'Blog categories', ''),
(181, 6, 'Blog categories', ''),
(181, 8, 'Blog categories', ''),
(182, 1, 'Blog Tags', ''),
(182, 6, 'Blog Tags', ''),
(182, 8, 'Blog Tags', ''),
(183, 1, 'Blog Archives', ''),
(183, 6, 'Blog Archives', ''),
(183, 8, 'Blog Archives', ''),
(184, 1, 'Category - Left sidebar', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=left'),
(184, 6, 'Category - Left sidebar', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=left'),
(184, 8, 'Category - Left sidebar', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=left'),
(185, 1, 'Category - Right sidebar', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=right'),
(185, 6, 'Category - Right sidebar', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=right'),
(185, 8, 'Category - Right sidebar', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=right'),
(186, 1, 'Category - No sidebar', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no'),
(186, 6, 'Category - No sidebar', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no'),
(186, 8, 'Category - No sidebar', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no'),
(187, 1, '2 Columns', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no&layout=category-layout-2columns'),
(187, 6, '2 Columns', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no&layout=category-layout-default'),
(187, 8, '2 Columns', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no&layout=category-layout-default'),
(188, 1, '3 Columns', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no&layout=category-layout-3columns'),
(188, 6, '3 Columns', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no&layout=category-layout-3columns'),
(188, 8, '3 Columns', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no&layout=category-layout-3columns'),
(189, 1, '4 Columns', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no&layout=category-layout-4columns'),
(189, 6, '4 Columns', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no&layout=category-layout-4columns'),
(189, 8, '4 Columns', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no&layout=category-layout-4columns'),
(190, 1, 'Left sidebar', 'index.php?fc=module&module=jmsblog&category_slug=news&post_id=2&controller=post&id_lang=1&sidebar=left'),
(190, 6, 'Left sidebar', 'index.php?fc=module&module=jmsblog&category_slug=news&post_id=13&controller=post&id_lang=1&sidebar=left'),
(190, 8, 'Left sidebar', 'index.php?fc=module&module=jmsblog&category_slug=news&post_id=13&controller=post&id_lang=1&sidebar=left'),
(191, 1, 'Right sidebar', 'index.php?fc=module&module=jmsblog&category_slug=news&post_id=2&controller=post&id_lang=1&sidebar=right'),
(191, 6, 'Right sidebar', 'index.php?fc=module&module=jmsblog&category_slug=news&post_id=13&controller=post&id_lang=1&sidebar=right'),
(191, 8, 'Right sidebar', 'index.php?fc=module&module=jmsblog&category_slug=news&post_id=13&controller=post&id_lang=1&sidebar=right'),
(192, 1, 'No Sidebar', 'index.php?fc=module&module=jmsblog&category_slug=news&post_id=2&controller=post&id_lang=1&sidebar=no'),
(192, 6, 'No Sidebar', 'index.php?fc=module&module=jmsblog&category_slug=news&post_id=13&controller=post&id_lang=1&sidebar=no'),
(192, 8, 'No Sidebar', 'index.php?fc=module&module=jmsblog&category_slug=news&post_id=13&controller=post&id_lang=1&sidebar=no'),
(193, 1, 'Categories - Left sidebar', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=left'),
(193, 6, 'Categories - Left sidebar', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=left'),
(193, 8, 'Categories - Left sidebar', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=left'),
(194, 1, 'Categories - Right sidebar', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=right'),
(194, 6, 'Categories - Right sidebar', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=right'),
(194, 8, 'Categories - Right sidebar', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=right'),
(195, 1, 'Categories - No sidebar', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=no'),
(195, 6, 'Categories - No sidebar', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=no'),
(195, 8, 'Categories - No sidebar', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=no'),
(196, 1, '2 Columns', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=left'),
(196, 6, '2 Columns', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=left'),
(196, 8, '2 Columns', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=left'),
(197, 1, '3 Columns', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=no&layout=categories-layout-3columns'),
(197, 6, '3 Columns', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=no&layout=categories-layout-3columns'),
(197, 8, '3 Columns', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=no&layout=categories-layout-3columns'),
(198, 1, '4 Columns', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=no&layout=categories-layout-4columns'),
(198, 6, '4 Columns', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=no&layout=categories-layout-4columns'),
(198, 8, '4 Columns', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=no&layout=categories-layout-4columns'),
(84, 6, 'Home', 'index.php'),
(84, 8, 'Home', 'index.php'),
(89, 6, 'Contact', 'index.php?controller=contact'),
(90, 6, 'Home 1', 'index.php?settingpanel=1&jpb_homepage=6'),
(91, 6, 'Home 2', 'index.php?settingpanel=1&jpb_homepage=6'),
(92, 6, 'Home 3', 'index.php?settingpanel=1&jpb_homepage=7'),
(93, 6, 'Home 4', 'index.php?settingpanel=1&jpb_homepage=8'),
(94, 6, 'Home 5', 'index.php?settingpanel=1&jpb_homepage=9'),
(95, 6, 'Home 6', 'index.php?settingpanel=1&jpb_homepage=10'),
(96, 6, 'Home 7', 'index.php?settingpanel=1&jpb_homepage=11'),
(97, 6, 'Home 8', 'index.php?settingpanel=1&jpb_homepage=12'),
(99, 6, 'Inforgraphic', '#'),
(99, 8, 'Inforgraphic', '#'),
(100, 6, 'Our Store', '#'),
(100, 8, 'Our Store', '#'),
(101, 6, 'Search Page', 'index.php?controller=search&search_query=adiva'),
(102, 6, 'Compare page', 'index.php?controller=products-comparison'),
(105, 6, '404 Page', 'index.php?controller=404'),
(112, 6, 'Women', '#'),
(112, 8, 'Women', '#'),
(113, 6, 'Dresess', '#'),
(113, 8, 'Dresess', '#'),
(114, 6, 'Skinny', '#'),
(114, 8, 'Skinny', '#'),
(115, 6, 'High-Heels', '#'),
(115, 8, 'High-Heels', '#'),
(116, 6, 'Jumpsuits', '#'),
(116, 8, 'Jumpsuits', '#'),
(117, 6, 'Knitwear', '#'),
(117, 8, 'Knitwear', '#'),
(118, 6, 'Gymwear', '#'),
(118, 8, 'Gymwear', '#'),
(119, 6, 'Accessories', '#'),
(119, 8, 'Accessories', '#'),
(120, 6, 'Shoes & Bags', '#'),
(120, 8, 'Shoes & Bags', '#'),
(121, 6, 'Sunglasses', '#'),
(121, 8, 'Sunglasses', '#'),
(122, 6, 'Watches & Jewelry', '#'),
(122, 8, 'Watches & Jewelry', '#'),
(123, 6, 'Scarves & Gloves', '#'),
(123, 8, 'Scarves & Gloves', '#'),
(124, 6, 'Hats & Ties', '#'),
(124, 8, 'Hats & Ties', '#'),
(125, 6, 'Belts', '#'),
(125, 8, 'Belts', '#'),
(128, 6, 'Men', '#'),
(128, 8, 'Men', '#'),
(129, 6, 'Blazers', '#'),
(129, 8, 'Blazers', '#'),
(130, 6, 'Trousers', '#'),
(130, 8, 'Trousers', '#'),
(131, 6, 'T-Shirts', '#'),
(131, 8, 'T-Shirts', '#'),
(132, 6, 'Polo-Shirts', '#'),
(132, 8, 'Polo-Shirts', '#'),
(133, 6, 'Short', '#'),
(133, 8, 'Short', '#'),
(134, 6, 'Jeans', '#'),
(134, 8, 'Jeans', '#'),
(137, 6, 'Polo-Shirts', '#'),
(137, 8, 'Polo-Shirts', '#'),
(138, 6, 'Jeans', '#'),
(138, 8, 'Jeans', '#'),
(139, 6, 'Dresess', '#'),
(139, 8, 'Dresess', '#'),
(140, 6, 'Shorts', '#'),
(140, 8, 'Shorts', '#'),
(141, 6, 'Trousers', '#'),
(141, 8, 'Trousers', '#'),
(142, 6, 'Sweatshirts', '#'),
(142, 8, 'Sweatshirts', '#'),
(200, 1, 'Bicycle Home', '#'),
(202, 1, 'Digital Home', '#'),
(204, 1, 'Fashion Home', '#'),
(206, 1, 'Food Home', '#'),
(207, 1, 'Furniture Home V.1', 'index.php?settingpanel=1&jpb_homepage=9'),
(209, 1, 'Furniture Home', '#'),
(210, 1, 'Furniture Home V.2', 'index.php?settingpanel=1&jpb_homepage=10'),
(212, 1, 'Jewellry Home', '#'),
(213, 1, 'Jewellry Home V.1', 'index.php?settingpanel=1&jpb_homepage=11'),
(214, 1, 'Jewellry Home V.2', 'index.php?settingpanel=1&jpb_homepage=12'),
(216, 1, 'Shoes Home V.1', 'index.php?settingpanel=1&jpb_homepage=13'),
(217, 1, 'Shoes Home', '#'),
(218, 1, 'Shoes Home V.2', 'index.php?settingpanel=1&jpb_homepage=14'),
(220, 1, 'Sunglass Home V.1', 'index.php?settingpanel=1&jpb_homepage=15'),
(221, 1, 'Sungglass Home', '#'),
(224, 1, 'Tools Home V.1', 'index.php?settingpanel=1&jpb_homepage=17'),
(225, 1, 'Tools Home', '#'),
(226, 1, 'Tools Home V.2', 'index.php?settingpanel=1&jpb_homepage=18'),
(228, 1, 'Watches Home V.1', 'index.php?settingpanel=1&jpb_homepage=19'),
(229, 1, 'Watches Home', '#'),
(230, 1, 'Watches Home V.2', 'index.php?settingpanel=1&jpb_homepage=20'),
(231, 1, 'Sunglass Home V.2', 'index.php?settingpanel=1&jpb_homepage=16'),
(232, 1, 'Accessories & supplies', ''),
(233, 1, 'Playstation 4 Consoles', ''),
(234, 1, '3D glasses', ''),
(235, 1, 'virtual reality headsets', ''),
(236, 1, 'PC Accessories', ''),
(241, 1, 'Jeans', ''),
(242, 1, 'Denim Jackets', ''),
(245, 1, 'Speakers ', ''),
(246, 1, 'Headsets ', ''),
(247, 1, 'Product Box Gutter', '#'),
(248, 1, 'No Gutter (0px)', 'index.php?id_category=10&controller=category&id_lang=1&jpb_gutterwidth=0&sidebar=left'),
(249, 1, 'Small Gutter (10px)', 'index.php?id_category=10&controller=category&id_lang=1&jpb_gutterwidth=10&sidebar=left'),
(250, 1, 'Medium Gutter (20px)', 'index.php?id_category=10&controller=category&id_lang=1&jpb_gutterwidth=20&sidebar=left'),
(251, 1, 'Gutter Default (30px)', 'index.php?id_category=10&controller=category&id_lang=1&sidebar=left'),
(252, 1, 'Large Gutter (40px)', 'index.php?id_category=10&controller=category&id_lang=1&jpb_gutterwidth=40&sidebar=left'),
(253, 1, 'Extra Large Gutter (60px)', 'index.php?id_category=10&controller=category&id_lang=1&jpb_gutterwidth=60&sidebar=no'),
(84, 2, 'Home', 'index.php'),
(85, 2, 'Shop', ''),
(86, 2, 'Products', ''),
(87, 2, 'Pages', ''),
(88, 2, 'Blog', ''),
(89, 2, 'Contact', 'index.php?controller=contact'),
(90, 2, 'Bicycle Home V.1', 'index.php?settingpanel=1&jpb_homepage=1'),
(91, 2, 'Bicycle Home V.2', 'index.php?settingpanel=1&jpb_homepage=2'),
(92, 2, 'Digital Home V.1', 'index.php?settingpanel=1&jpb_homepage=3'),
(93, 2, 'Digital Home V.2', 'index.php?settingpanel=1&jpb_homepage=4'),
(94, 2, 'Fashion Home V.1', 'index.php?settingpanel=1&jpb_homepage=5'),
(95, 2, 'Fashion Home V.2', 'index.php?settingpanel=1&jpb_homepage=6'),
(96, 2, 'Food  Home V.1', 'index.php?settingpanel=1&jpb_homepage=7'),
(97, 2, 'Food  Home V.2', 'index.php?settingpanel=1&jpb_homepage=8'),
(98, 2, 'Typography', ''),
(99, 2, 'Wishlist Page', 'index.php?fc=module&module=jmswishlist&controller=mywishlist&id_lang=1'),
(100, 2, 'Our Store', 'index.php?controller=stores'),
(101, 2, 'Search Page', 'index.php?controller=search&search_query=gop'),
(102, 2, 'Site Map', 'index.php?controller=sitemap'),
(103, 2, 'About Us', 'index.php?controller=new-products'),
(104, 2, 'Best Sales', 'index.php?controller=best-sales'),
(105, 2, '404 Page', 'index.php?controller=404'),
(111, 2, 'LG Image', ''),
(112, 2, 'audio & television', '#'),
(113, 2, '3D glasses', '#'),
(114, 2, 'virtual reality headsets', '#'),
(115, 2, 'PC Accessories', '#'),
(116, 2, 'Video Glasses', '#'),
(117, 2, 'PC game headsets', '#'),
(118, 2, 'video game VR headsets', '#'),
(119, 2, 'Accessories', '#'),
(120, 2, 'Shoes & Bags', '#'),
(121, 2, 'Sunglasses', '#'),
(122, 2, 'Watches & Jewelry', '#'),
(123, 2, 'Scarves & Gloves', '#'),
(124, 2, 'Hats & Ties', '#'),
(125, 2, 'Belts', '#'),
(126, 2, 'Sony Image', ''),
(127, 2, 'Samsung Image', ''),
(128, 2, 'Men', '#'),
(129, 2, 'Blazers', '#'),
(130, 2, 'Trousers', '#'),
(131, 2, 'T-Shirts', '#'),
(132, 2, 'Polo-Shirts', '#'),
(133, 2, 'Short', '#'),
(134, 2, 'Jeans', '#'),
(135, 2, 'Discount Image', ''),
(137, 2, 'Polo-Shirts', '#'),
(138, 2, 'Jeans', '#'),
(139, 2, 'Dresess', '#'),
(140, 2, 'Shorts', '#'),
(141, 2, 'Trousers', '#'),
(142, 2, 'Sweatshirts', '#'),
(143, 2, 'Product Layout', '#'),
(144, 2, 'Left sidebar', 'index.php?id_product=22&id_product_attribute=57&rewrite=hp-lp3065&controller=product&id_lang=1&sidebar=left'),
(145, 2, 'Right sidebar', 'index.php?id_product=22&id_product_attribute=57&rewrite=hp-lp3065&controller=product&id_lang=1&sidebar=right'),
(146, 2, 'No Sidebar', 'index.php?id_product=22&id_product_attribute=57&rewrite=hp-lp3065&controller=product&id_lang=1&sidebar=no'),
(147, 2, '3 Columns Layout', 'index.php?id_product=22&id_product_attribute=57&rewrite=hp-lp3065&controller=product&id_lang=1&sidebar=no&layout=product-layout-3columns'),
(148, 2, '2 Columns Layout', 'index.php?id_product=22&id_product_attribute=57&rewrite=hp-lp3065&controller=product&id_lang=1&sidebar=left'),
(151, 2, 'Product Type', '#'),
(152, 2, 'Virtual Product', ''),
(153, 2, 'Standard Product', ''),
(154, 2, 'Pack Products', ''),
(155, 2, 'Product Color Swatch', ''),
(156, 2, 'Product with custom tab', ''),
(157, 2, 'Product with video', ''),
(158, 2, 'Product out of stock', ''),
(159, 2, 'Add to cart', '#'),
(160, 2, 'Ajax Default', 'index.php?jpb_addtocart=default'),
(161, 2, 'Ajax + Preview Popup', 'index.php?jpb_addtocart=ajax_popup'),
(162, 2, 'Ajax + Image Moving', 'index.php?jpb_addtocart=ajax_moveimage'),
(163, 2, 'Ajax + Cart at Bottom', 'index.php?jpb_addtocart=ajax_cartbottom'),
(164, 2, 'Ajax + Cart at Sidebar', 'index.php?jpb_addtocart=ajax_cartsidebar'),
(165, 2, 'No Ajax', 'index.php?jpb_addtocart=no_ajax'),
(166, 2, 'Category Layout', '#'),
(167, 2, 'Left sidebar', 'index.php?id_category=10&controller=category&id_lang=1&sidebar=left'),
(168, 2, 'Right sidebar', 'index.php?id_category=10&controller=category&id_lang=1&sidebar=right'),
(169, 2, 'No Sidebar', 'index.php?id_category=10&controller=category&id_lang=1&sidebar=no'),
(170, 2, 'Category Banner', 'index.php?id_category=112&controller=category&id_lang=1&sidebar=left&layout=category-layout-banner'),
(171, 2, ' Banner and Descriptions', 'index.php?id_category=112&controller=category&id_lang=1&sidebar=left&layout=category-layout-bannerandesc'),
(172, 2, 'Category Descriptions', 'index.php?id_category=112&controller=category&id_lang=1&sidebar=left&layout=category-layout-desc'),
(173, 2, 'Grid 2 Colums', 'index.php?id_category=10&controller=category&id_lang=1&ppr=2'),
(174, 2, 'Grid 3 Colums', 'index.php?id_category=10&controller=category&id_lang=1&ppr=3'),
(175, 2, 'Grid 4 Colums', 'index.php?id_category=10&controller=category&id_lang=1&ppr=4'),
(176, 2, 'Grid 5 Colums', 'index.php?id_category=10&controller=category&id_lang=1&sidebar=no&ppr=5'),
(177, 2, 'Grid 6 Colums', 'index.php?id_category=10&controller=category&id_lang=1&sidebar=no&ppr=6'),
(178, 2, 'List Layout', 'index.php?id_category=10&controller=category&id_lang=1&jpb_grid=0&sidebar=left'),
(179, 2, 'Blog Category', ''),
(180, 2, 'Blog single post', ''),
(181, 2, 'Blog categories', ''),
(182, 2, 'Blog Tags', ''),
(183, 2, 'Blog Archives', ''),
(184, 2, 'Category - Left sidebar', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=left'),
(185, 2, 'Category - Right sidebar', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=right'),
(186, 2, 'Category - No sidebar', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no'),
(187, 2, '2 Columns', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no&layout=category-layout-2columns'),
(188, 2, '3 Columns', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no&layout=category-layout-3columns'),
(189, 2, '4 Columns', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no&layout=category-layout-4columns'),
(190, 2, 'Left sidebar', 'index.php?fc=module&module=jmsblog&category_slug=news&post_id=2&controller=post&id_lang=1&sidebar=left'),
(191, 2, 'Right sidebar', 'index.php?fc=module&module=jmsblog&category_slug=news&post_id=2&controller=post&id_lang=1&sidebar=right'),
(192, 2, 'No Sidebar', 'index.php?fc=module&module=jmsblog&category_slug=news&post_id=2&controller=post&id_lang=1&sidebar=no'),
(193, 2, 'Categories - Left sidebar', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=left'),
(194, 2, 'Categories - Right sidebar', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=right'),
(195, 2, 'Categories - No sidebar', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=no'),
(196, 2, '2 Columns', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=left'),
(197, 2, '3 Columns', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=no&layout=categories-layout-3columns'),
(198, 2, '4 Columns', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=no&layout=categories-layout-4columns'),
(200, 2, 'Bicycle Home', '#'),
(202, 2, 'Digital Home', '#'),
(204, 2, 'Fashion Home', '#'),
(206, 2, 'Food Home', '#'),
(207, 2, 'Furniture Home V.1', 'index.php?settingpanel=1&jpb_homepage=9'),
(209, 2, 'Furniture Home', '#'),
(210, 2, 'Furniture Home V.2', 'index.php?settingpanel=1&jpb_homepage=10'),
(212, 2, 'Jewellry Home', '#'),
(213, 2, 'Jewellry Home V.1', 'index.php?settingpanel=1&jpb_homepage=11'),
(214, 2, 'Jewellry Home V.2', 'index.php?settingpanel=1&jpb_homepage=12'),
(216, 2, 'Shoes Home V.1', 'index.php?settingpanel=1&jpb_homepage=13'),
(217, 2, 'Shoes Home', '#'),
(218, 2, 'Shoes Home V.2', 'index.php?settingpanel=1&jpb_homepage=14'),
(220, 2, 'Sunglass Home V.1', 'index.php?settingpanel=1&jpb_homepage=15'),
(221, 2, 'Sungglass Home', '#'),
(224, 2, 'Tools Home V.1', 'index.php?settingpanel=1&jpb_homepage=17'),
(225, 2, 'Tools Home', '#'),
(226, 2, 'Tools Home V.2', 'index.php?settingpanel=1&jpb_homepage=18'),
(228, 2, 'Watches Home V.1', 'index.php?settingpanel=1&jpb_homepage=19'),
(229, 2, 'Watches Home', '#'),
(230, 2, 'Watches Home V.2', 'index.php?settingpanel=1&jpb_homepage=20'),
(231, 2, 'Sunglass Home V.2', 'index.php?settingpanel=1&jpb_homepage=16'),
(232, 2, 'Accessories & supplies', ''),
(233, 2, 'Playstation 4 Consoles', ''),
(234, 2, '3D glasses', ''),
(235, 2, 'virtual reality headsets', ''),
(236, 2, 'PC Accessories', ''),
(241, 2, 'Jeans', ''),
(242, 2, 'Denim Jackets', ''),
(245, 2, 'Speakers ', ''),
(246, 2, 'Headsets ', ''),
(247, 2, 'Product Box Gutter', '#'),
(248, 2, 'No Gutter (0px)', 'index.php?id_category=10&controller=category&id_lang=1&jpb_gutterwidth=0&sidebar=left'),
(249, 2, 'Small Gutter (10px)', 'index.php?id_category=10&controller=category&id_lang=1&jpb_gutterwidth=10&sidebar=left'),
(250, 2, 'Medium Gutter (20px)', 'index.php?id_category=10&controller=category&id_lang=1&jpb_gutterwidth=20&sidebar=left'),
(251, 2, 'Gutter Default (30px)', 'index.php?id_category=10&controller=category&id_lang=1&sidebar=left'),
(252, 2, 'Large Gutter (40px)', 'index.php?id_category=10&controller=category&id_lang=1&jpb_gutterwidth=40&sidebar=left'),
(253, 2, 'Extra Large Gutter (60px)', 'index.php?id_category=10&controller=category&id_lang=1&jpb_gutterwidth=60&sidebar=no'),
(84, 3, 'Home', 'index.php'),
(85, 3, 'Shop', ''),
(86, 3, 'Products', ''),
(87, 3, 'Pages', ''),
(88, 3, 'Blog', ''),
(89, 3, 'Contact', 'index.php?controller=contact'),
(90, 3, 'Bicycle Home V.1', 'index.php?settingpanel=1&jpb_homepage=1'),
(91, 3, 'Bicycle Home V.2', 'index.php?settingpanel=1&jpb_homepage=2'),
(92, 3, 'Digital Home V.1', 'index.php?settingpanel=1&jpb_homepage=3'),
(93, 3, 'Digital Home V.2', 'index.php?settingpanel=1&jpb_homepage=4'),
(94, 3, 'Fashion Home V.1', 'index.php?settingpanel=1&jpb_homepage=5'),
(95, 3, 'Fashion Home V.2', 'index.php?settingpanel=1&jpb_homepage=6'),
(96, 3, 'Food  Home V.1', 'index.php?settingpanel=1&jpb_homepage=7'),
(97, 3, 'Food  Home V.2', 'index.php?settingpanel=1&jpb_homepage=8'),
(98, 3, 'Typography', ''),
(99, 3, 'Wishlist Page', 'index.php?fc=module&module=jmswishlist&controller=mywishlist&id_lang=1'),
(100, 3, 'Our Store', 'index.php?controller=stores'),
(101, 3, 'Search Page', 'index.php?controller=search&search_query=gop'),
(102, 3, 'Site Map', 'index.php?controller=sitemap'),
(103, 3, 'About Us', 'index.php?controller=new-products'),
(104, 3, 'Best Sales', 'index.php?controller=best-sales'),
(105, 3, '404 Page', 'index.php?controller=404'),
(111, 3, 'LG Image', ''),
(112, 3, 'audio & television', '#'),
(113, 3, '3D glasses', '#'),
(114, 3, 'virtual reality headsets', '#'),
(115, 3, 'PC Accessories', '#'),
(116, 3, 'Video Glasses', '#'),
(117, 3, 'PC game headsets', '#'),
(118, 3, 'video game VR headsets', '#'),
(119, 3, 'Accessories', '#'),
(120, 3, 'Shoes & Bags', '#'),
(121, 3, 'Sunglasses', '#'),
(122, 3, 'Watches & Jewelry', '#'),
(123, 3, 'Scarves & Gloves', '#'),
(124, 3, 'Hats & Ties', '#'),
(125, 3, 'Belts', '#'),
(126, 3, 'Sony Image', ''),
(127, 3, 'Samsung Image', ''),
(128, 3, 'Men', '#'),
(129, 3, 'Blazers', '#'),
(130, 3, 'Trousers', '#'),
(131, 3, 'T-Shirts', '#'),
(132, 3, 'Polo-Shirts', '#'),
(133, 3, 'Short', '#'),
(134, 3, 'Jeans', '#'),
(135, 3, 'Discount Image', ''),
(137, 3, 'Polo-Shirts', '#'),
(138, 3, 'Jeans', '#'),
(139, 3, 'Dresess', '#'),
(140, 3, 'Shorts', '#'),
(141, 3, 'Trousers', '#'),
(142, 3, 'Sweatshirts', '#'),
(143, 3, 'Product Layout', '#'),
(144, 3, 'Left sidebar', 'index.php?id_product=22&id_product_attribute=57&rewrite=hp-lp3065&controller=product&id_lang=1&sidebar=left'),
(145, 3, 'Right sidebar', 'index.php?id_product=22&id_product_attribute=57&rewrite=hp-lp3065&controller=product&id_lang=1&sidebar=right'),
(146, 3, 'No Sidebar', 'index.php?id_product=22&id_product_attribute=57&rewrite=hp-lp3065&controller=product&id_lang=1&sidebar=no'),
(147, 3, '3 Columns Layout', 'index.php?id_product=22&id_product_attribute=57&rewrite=hp-lp3065&controller=product&id_lang=1&sidebar=no&layout=product-layout-3columns'),
(148, 3, '2 Columns Layout', 'index.php?id_product=22&id_product_attribute=57&rewrite=hp-lp3065&controller=product&id_lang=1&sidebar=left'),
(151, 3, 'Product Type', '#'),
(152, 3, 'Virtual Product', ''),
(153, 3, 'Standard Product', ''),
(154, 3, 'Pack Products', ''),
(155, 3, 'Product Color Swatch', ''),
(156, 3, 'Product with custom tab', ''),
(157, 3, 'Product with video', ''),
(158, 3, 'Product out of stock', ''),
(159, 3, 'Add to cart', '#'),
(160, 3, 'Ajax Default', 'index.php?jpb_addtocart=default'),
(161, 3, 'Ajax + Preview Popup', 'index.php?jpb_addtocart=ajax_popup'),
(162, 3, 'Ajax + Image Moving', 'index.php?jpb_addtocart=ajax_moveimage'),
(163, 3, 'Ajax + Cart at Bottom', 'index.php?jpb_addtocart=ajax_cartbottom'),
(164, 3, 'Ajax + Cart at Sidebar', 'index.php?jpb_addtocart=ajax_cartsidebar'),
(165, 3, 'No Ajax', 'index.php?jpb_addtocart=no_ajax'),
(166, 3, 'Category Layout', '#'),
(167, 3, 'Left sidebar', 'index.php?id_category=10&controller=category&id_lang=1&sidebar=left'),
(168, 3, 'Right sidebar', 'index.php?id_category=10&controller=category&id_lang=1&sidebar=right'),
(169, 3, 'No Sidebar', 'index.php?id_category=10&controller=category&id_lang=1&sidebar=no'),
(170, 3, 'Category Banner', 'index.php?id_category=112&controller=category&id_lang=1&sidebar=left&layout=category-layout-banner'),
(171, 3, ' Banner and Descriptions', 'index.php?id_category=112&controller=category&id_lang=1&sidebar=left&layout=category-layout-bannerandesc'),
(172, 3, 'Category Descriptions', 'index.php?id_category=112&controller=category&id_lang=1&sidebar=left&layout=category-layout-desc'),
(173, 3, 'Grid 2 Colums', 'index.php?id_category=10&controller=category&id_lang=1&ppr=2'),
(174, 3, 'Grid 3 Colums', 'index.php?id_category=10&controller=category&id_lang=1&ppr=3'),
(175, 3, 'Grid 4 Colums', 'index.php?id_category=10&controller=category&id_lang=1&ppr=4'),
(176, 3, 'Grid 5 Colums', 'index.php?id_category=10&controller=category&id_lang=1&sidebar=no&ppr=5'),
(177, 3, 'Grid 6 Colums', 'index.php?id_category=10&controller=category&id_lang=1&sidebar=no&ppr=6'),
(178, 3, 'List Layout', 'index.php?id_category=10&controller=category&id_lang=1&jpb_grid=0&sidebar=left'),
(179, 3, 'Blog Category', ''),
(180, 3, 'Blog single post', ''),
(181, 3, 'Blog categories', ''),
(182, 3, 'Blog Tags', ''),
(183, 3, 'Blog Archives', ''),
(184, 3, 'Category - Left sidebar', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=left'),
(185, 3, 'Category - Right sidebar', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=right'),
(186, 3, 'Category - No sidebar', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no'),
(187, 3, '2 Columns', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no&layout=category-layout-2columns'),
(188, 3, '3 Columns', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no&layout=category-layout-3columns'),
(189, 3, '4 Columns', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no&layout=category-layout-4columns'),
(190, 3, 'Left sidebar', 'index.php?fc=module&module=jmsblog&category_slug=news&post_id=2&controller=post&id_lang=1&sidebar=left'),
(191, 3, 'Right sidebar', 'index.php?fc=module&module=jmsblog&category_slug=news&post_id=2&controller=post&id_lang=1&sidebar=right'),
(192, 3, 'No Sidebar', 'index.php?fc=module&module=jmsblog&category_slug=news&post_id=2&controller=post&id_lang=1&sidebar=no'),
(193, 3, 'Categories - Left sidebar', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=left'),
(194, 3, 'Categories - Right sidebar', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=right'),
(195, 3, 'Categories - No sidebar', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=no'),
(196, 3, '2 Columns', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=left'),
(197, 3, '3 Columns', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=no&layout=categories-layout-3columns'),
(198, 3, '4 Columns', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=no&layout=categories-layout-4columns'),
(200, 3, 'Bicycle Home', '#'),
(202, 3, 'Digital Home', '#'),
(204, 3, 'Fashion Home', '#'),
(206, 3, 'Food Home', '#'),
(207, 3, 'Furniture Home V.1', 'index.php?settingpanel=1&jpb_homepage=9'),
(209, 3, 'Furniture Home', '#'),
(210, 3, 'Furniture Home V.2', 'index.php?settingpanel=1&jpb_homepage=10'),
(212, 3, 'Jewellry Home', '#'),
(213, 3, 'Jewellry Home V.1', 'index.php?settingpanel=1&jpb_homepage=11'),
(214, 3, 'Jewellry Home V.2', 'index.php?settingpanel=1&jpb_homepage=12'),
(216, 3, 'Shoes Home V.1', 'index.php?settingpanel=1&jpb_homepage=13'),
(217, 3, 'Shoes Home', '#'),
(218, 3, 'Shoes Home V.2', 'index.php?settingpanel=1&jpb_homepage=14'),
(220, 3, 'Sunglass Home V.1', 'index.php?settingpanel=1&jpb_homepage=15'),
(221, 3, 'Sungglass Home', '#'),
(224, 3, 'Tools Home V.1', 'index.php?settingpanel=1&jpb_homepage=17'),
(225, 3, 'Tools Home', '#'),
(226, 3, 'Tools Home V.2', 'index.php?settingpanel=1&jpb_homepage=18'),
(228, 3, 'Watches Home V.1', 'index.php?settingpanel=1&jpb_homepage=19'),
(229, 3, 'Watches Home', '#'),
(230, 3, 'Watches Home V.2', 'index.php?settingpanel=1&jpb_homepage=20'),
(231, 3, 'Sunglass Home V.2', 'index.php?settingpanel=1&jpb_homepage=16'),
(232, 3, 'Accessories & supplies', ''),
(233, 3, 'Playstation 4 Consoles', ''),
(234, 3, '3D glasses', ''),
(235, 3, 'virtual reality headsets', ''),
(236, 3, 'PC Accessories', ''),
(241, 3, 'Jeans', ''),
(242, 3, 'Denim Jackets', ''),
(245, 3, 'Speakers ', ''),
(246, 3, 'Headsets ', ''),
(247, 3, 'Product Box Gutter', '#'),
(248, 3, 'No Gutter (0px)', 'index.php?id_category=10&controller=category&id_lang=1&jpb_gutterwidth=0&sidebar=left'),
(249, 3, 'Small Gutter (10px)', 'index.php?id_category=10&controller=category&id_lang=1&jpb_gutterwidth=10&sidebar=left'),
(250, 3, 'Medium Gutter (20px)', 'index.php?id_category=10&controller=category&id_lang=1&jpb_gutterwidth=20&sidebar=left'),
(251, 3, 'Gutter Default (30px)', 'index.php?id_category=10&controller=category&id_lang=1&sidebar=left'),
(252, 3, 'Large Gutter (40px)', 'index.php?id_category=10&controller=category&id_lang=1&jpb_gutterwidth=40&sidebar=left'),
(253, 3, 'Extra Large Gutter (60px)', 'index.php?id_category=10&controller=category&id_lang=1&jpb_gutterwidth=60&sidebar=no'),
(84, 4, 'Home', 'index.php'),
(85, 4, 'Shop', ''),
(86, 4, 'Products', ''),
(87, 4, 'Pages', ''),
(88, 4, 'Blog', ''),
(89, 4, 'Contact', 'index.php?controller=contact'),
(90, 4, 'Bicycle Home V.1', 'index.php?settingpanel=1&jpb_homepage=1'),
(91, 4, 'Bicycle Home V.2', 'index.php?settingpanel=1&jpb_homepage=2'),
(92, 4, 'Digital Home V.1', 'index.php?settingpanel=1&jpb_homepage=3'),
(93, 4, 'Digital Home V.2', 'index.php?settingpanel=1&jpb_homepage=4'),
(94, 4, 'Fashion Home V.1', 'index.php?settingpanel=1&jpb_homepage=5'),
(95, 4, 'Fashion Home V.2', 'index.php?settingpanel=1&jpb_homepage=6'),
(96, 4, 'Food  Home V.1', 'index.php?settingpanel=1&jpb_homepage=7'),
(97, 4, 'Food  Home V.2', 'index.php?settingpanel=1&jpb_homepage=8'),
(98, 4, 'Typography', ''),
(99, 4, 'Wishlist Page', 'index.php?fc=module&module=jmswishlist&controller=mywishlist&id_lang=1'),
(100, 4, 'Our Store', 'index.php?controller=stores'),
(101, 4, 'Search Page', 'index.php?controller=search&search_query=gop'),
(102, 4, 'Site Map', 'index.php?controller=sitemap'),
(103, 4, 'About Us', 'index.php?controller=new-products'),
(104, 4, 'Best Sales', 'index.php?controller=best-sales'),
(105, 4, '404 Page', 'index.php?controller=404'),
(111, 4, 'LG Image', ''),
(112, 4, 'audio & television', '#'),
(113, 4, '3D glasses', '#'),
(114, 4, 'virtual reality headsets', '#'),
(115, 4, 'PC Accessories', '#'),
(116, 4, 'Video Glasses', '#'),
(117, 4, 'PC game headsets', '#'),
(118, 4, 'video game VR headsets', '#'),
(119, 4, 'Accessories', '#'),
(120, 4, 'Shoes & Bags', '#'),
(121, 4, 'Sunglasses', '#'),
(122, 4, 'Watches & Jewelry', '#'),
(123, 4, 'Scarves & Gloves', '#'),
(124, 4, 'Hats & Ties', '#'),
(125, 4, 'Belts', '#'),
(126, 4, 'Sony Image', ''),
(127, 4, 'Samsung Image', ''),
(128, 4, 'Men', '#'),
(129, 4, 'Blazers', '#'),
(130, 4, 'Trousers', '#'),
(131, 4, 'T-Shirts', '#'),
(132, 4, 'Polo-Shirts', '#'),
(133, 4, 'Short', '#'),
(134, 4, 'Jeans', '#'),
(135, 4, 'Discount Image', ''),
(137, 4, 'Polo-Shirts', '#'),
(138, 4, 'Jeans', '#'),
(139, 4, 'Dresess', '#'),
(140, 4, 'Shorts', '#'),
(141, 4, 'Trousers', '#'),
(142, 4, 'Sweatshirts', '#'),
(143, 4, 'Product Layout', '#'),
(144, 4, 'Left sidebar', 'index.php?id_product=22&id_product_attribute=57&rewrite=hp-lp3065&controller=product&id_lang=1&sidebar=left'),
(145, 4, 'Right sidebar', 'index.php?id_product=22&id_product_attribute=57&rewrite=hp-lp3065&controller=product&id_lang=1&sidebar=right'),
(146, 4, 'No Sidebar', 'index.php?id_product=22&id_product_attribute=57&rewrite=hp-lp3065&controller=product&id_lang=1&sidebar=no'),
(147, 4, '3 Columns Layout', 'index.php?id_product=22&id_product_attribute=57&rewrite=hp-lp3065&controller=product&id_lang=1&sidebar=no&layout=product-layout-3columns'),
(148, 4, '2 Columns Layout', 'index.php?id_product=22&id_product_attribute=57&rewrite=hp-lp3065&controller=product&id_lang=1&sidebar=left'),
(151, 4, 'Product Type', '#'),
(152, 4, 'Virtual Product', ''),
(153, 4, 'Standard Product', ''),
(154, 4, 'Pack Products', ''),
(155, 4, 'Product Color Swatch', ''),
(156, 4, 'Product with custom tab', ''),
(157, 4, 'Product with video', ''),
(158, 4, 'Product out of stock', ''),
(159, 4, 'Add to cart', '#'),
(160, 4, 'Ajax Default', 'index.php?jpb_addtocart=default'),
(161, 4, 'Ajax + Preview Popup', 'index.php?jpb_addtocart=ajax_popup'),
(162, 4, 'Ajax + Image Moving', 'index.php?jpb_addtocart=ajax_moveimage'),
(163, 4, 'Ajax + Cart at Bottom', 'index.php?jpb_addtocart=ajax_cartbottom'),
(164, 4, 'Ajax + Cart at Sidebar', 'index.php?jpb_addtocart=ajax_cartsidebar'),
(165, 4, 'No Ajax', 'index.php?jpb_addtocart=no_ajax'),
(166, 4, 'Category Layout', '#'),
(167, 4, 'Left sidebar', 'index.php?id_category=10&controller=category&id_lang=1&sidebar=left'),
(168, 4, 'Right sidebar', 'index.php?id_category=10&controller=category&id_lang=1&sidebar=right'),
(169, 4, 'No Sidebar', 'index.php?id_category=10&controller=category&id_lang=1&sidebar=no'),
(170, 4, 'Category Banner', 'index.php?id_category=112&controller=category&id_lang=1&sidebar=left&layout=category-layout-banner'),
(171, 4, ' Banner and Descriptions', 'index.php?id_category=112&controller=category&id_lang=1&sidebar=left&layout=category-layout-bannerandesc'),
(172, 4, 'Category Descriptions', 'index.php?id_category=112&controller=category&id_lang=1&sidebar=left&layout=category-layout-desc'),
(173, 4, 'Grid 2 Colums', 'index.php?id_category=10&controller=category&id_lang=1&ppr=2'),
(174, 4, 'Grid 3 Colums', 'index.php?id_category=10&controller=category&id_lang=1&ppr=3'),
(175, 4, 'Grid 4 Colums', 'index.php?id_category=10&controller=category&id_lang=1&ppr=4'),
(176, 4, 'Grid 5 Colums', 'index.php?id_category=10&controller=category&id_lang=1&sidebar=no&ppr=5'),
(177, 4, 'Grid 6 Colums', 'index.php?id_category=10&controller=category&id_lang=1&sidebar=no&ppr=6'),
(178, 4, 'List Layout', 'index.php?id_category=10&controller=category&id_lang=1&jpb_grid=0&sidebar=left'),
(179, 4, 'Blog Category', ''),
(180, 4, 'Blog single post', ''),
(181, 4, 'Blog categories', ''),
(182, 4, 'Blog Tags', ''),
(183, 4, 'Blog Archives', ''),
(184, 4, 'Category - Left sidebar', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=left'),
(185, 4, 'Category - Right sidebar', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=right'),
(186, 4, 'Category - No sidebar', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no'),
(187, 4, '2 Columns', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no&layout=category-layout-2columns'),
(188, 4, '3 Columns', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no&layout=category-layout-3columns'),
(189, 4, '4 Columns', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no&layout=category-layout-4columns'),
(190, 4, 'Left sidebar', 'index.php?fc=module&module=jmsblog&category_slug=news&post_id=2&controller=post&id_lang=1&sidebar=left'),
(191, 4, 'Right sidebar', 'index.php?fc=module&module=jmsblog&category_slug=news&post_id=2&controller=post&id_lang=1&sidebar=right'),
(192, 4, 'No Sidebar', 'index.php?fc=module&module=jmsblog&category_slug=news&post_id=2&controller=post&id_lang=1&sidebar=no'),
(193, 4, 'Categories - Left sidebar', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=left'),
(194, 4, 'Categories - Right sidebar', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=right'),
(195, 4, 'Categories - No sidebar', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=no'),
(196, 4, '2 Columns', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=left'),
(197, 4, '3 Columns', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=no&layout=categories-layout-3columns'),
(198, 4, '4 Columns', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=no&layout=categories-layout-4columns'),
(200, 4, 'Bicycle Home', '#'),
(202, 4, 'Digital Home', '#'),
(204, 4, 'Fashion Home', '#'),
(206, 4, 'Food Home', '#'),
(207, 4, 'Furniture Home V.1', 'index.php?settingpanel=1&jpb_homepage=9'),
(209, 4, 'Furniture Home', '#'),
(210, 4, 'Furniture Home V.2', 'index.php?settingpanel=1&jpb_homepage=10'),
(212, 4, 'Jewellry Home', '#'),
(213, 4, 'Jewellry Home V.1', 'index.php?settingpanel=1&jpb_homepage=11'),
(214, 4, 'Jewellry Home V.2', 'index.php?settingpanel=1&jpb_homepage=12'),
(216, 4, 'Shoes Home V.1', 'index.php?settingpanel=1&jpb_homepage=13'),
(217, 4, 'Shoes Home', '#'),
(218, 4, 'Shoes Home V.2', 'index.php?settingpanel=1&jpb_homepage=14'),
(220, 4, 'Sunglass Home V.1', 'index.php?settingpanel=1&jpb_homepage=15'),
(221, 4, 'Sungglass Home', '#'),
(224, 4, 'Tools Home V.1', 'index.php?settingpanel=1&jpb_homepage=17'),
(225, 4, 'Tools Home', '#'),
(226, 4, 'Tools Home V.2', 'index.php?settingpanel=1&jpb_homepage=18'),
(228, 4, 'Watches Home V.1', 'index.php?settingpanel=1&jpb_homepage=19'),
(229, 4, 'Watches Home', '#'),
(230, 4, 'Watches Home V.2', 'index.php?settingpanel=1&jpb_homepage=20'),
(231, 4, 'Sunglass Home V.2', 'index.php?settingpanel=1&jpb_homepage=16'),
(232, 4, 'Accessories & supplies', ''),
(233, 4, 'Playstation 4 Consoles', ''),
(234, 4, '3D glasses', ''),
(235, 4, 'virtual reality headsets', ''),
(236, 4, 'PC Accessories', ''),
(241, 4, 'Jeans', ''),
(242, 4, 'Denim Jackets', ''),
(245, 4, 'Speakers ', ''),
(246, 4, 'Headsets ', ''),
(247, 4, 'Product Box Gutter', '#'),
(248, 4, 'No Gutter (0px)', 'index.php?id_category=10&controller=category&id_lang=1&jpb_gutterwidth=0&sidebar=left'),
(249, 4, 'Small Gutter (10px)', 'index.php?id_category=10&controller=category&id_lang=1&jpb_gutterwidth=10&sidebar=left'),
(250, 4, 'Medium Gutter (20px)', 'index.php?id_category=10&controller=category&id_lang=1&jpb_gutterwidth=20&sidebar=left'),
(251, 4, 'Gutter Default (30px)', 'index.php?id_category=10&controller=category&id_lang=1&sidebar=left'),
(252, 4, 'Large Gutter (40px)', 'index.php?id_category=10&controller=category&id_lang=1&jpb_gutterwidth=40&sidebar=left'),
(253, 4, 'Extra Large Gutter (60px)', 'index.php?id_category=10&controller=category&id_lang=1&jpb_gutterwidth=60&sidebar=no'),
(84, 5, 'Home', 'index.php'),
(85, 5, 'Shop', ''),
(86, 5, 'Products', ''),
(87, 5, 'Pages', ''),
(88, 5, 'Blog', ''),
(89, 5, 'Contact', 'index.php?controller=contact'),
(90, 5, 'Bicycle Home V.1', 'index.php?settingpanel=1&jpb_homepage=1'),
(91, 5, 'Bicycle Home V.2', 'index.php?settingpanel=1&jpb_homepage=2'),
(92, 5, 'Digital Home V.1', 'index.php?settingpanel=1&jpb_homepage=3'),
(93, 5, 'Digital Home V.2', 'index.php?settingpanel=1&jpb_homepage=4'),
(94, 5, 'Fashion Home V.1', 'index.php?settingpanel=1&jpb_homepage=5'),
(95, 5, 'Fashion Home V.2', 'index.php?settingpanel=1&jpb_homepage=6'),
(96, 5, 'Food  Home V.1', 'index.php?settingpanel=1&jpb_homepage=7'),
(97, 5, 'Food  Home V.2', 'index.php?settingpanel=1&jpb_homepage=8'),
(98, 5, 'Typography', ''),
(99, 5, 'Wishlist Page', 'index.php?fc=module&module=jmswishlist&controller=mywishlist&id_lang=1'),
(100, 5, 'Our Store', 'index.php?controller=stores'),
(101, 5, 'Search Page', 'index.php?controller=search&search_query=gop'),
(102, 5, 'Site Map', 'index.php?controller=sitemap'),
(103, 5, 'About Us', 'index.php?controller=new-products'),
(104, 5, 'Best Sales', 'index.php?controller=best-sales'),
(105, 5, '404 Page', 'index.php?controller=404'),
(111, 5, 'LG Image', ''),
(112, 5, 'audio & television', '#'),
(113, 5, '3D glasses', '#'),
(114, 5, 'virtual reality headsets', '#'),
(115, 5, 'PC Accessories', '#'),
(116, 5, 'Video Glasses', '#');
INSERT INTO `_DB_PREFIX_jmsmegamenu_lang` (`mitem_id`, `id_lang`, `name`, `menulink`) VALUES
(117, 5, 'PC game headsets', '#'),
(118, 5, 'video game VR headsets', '#'),
(119, 5, 'Accessories', '#'),
(120, 5, 'Shoes & Bags', '#'),
(121, 5, 'Sunglasses', '#'),
(122, 5, 'Watches & Jewelry', '#'),
(123, 5, 'Scarves & Gloves', '#'),
(124, 5, 'Hats & Ties', '#'),
(125, 5, 'Belts', '#'),
(126, 5, 'Sony Image', ''),
(127, 5, 'Samsung Image', ''),
(128, 5, 'Men', '#'),
(129, 5, 'Blazers', '#'),
(130, 5, 'Trousers', '#'),
(131, 5, 'T-Shirts', '#'),
(132, 5, 'Polo-Shirts', '#'),
(133, 5, 'Short', '#'),
(134, 5, 'Jeans', '#'),
(135, 5, 'Discount Image', ''),
(137, 5, 'Polo-Shirts', '#'),
(138, 5, 'Jeans', '#'),
(139, 5, 'Dresess', '#'),
(140, 5, 'Shorts', '#'),
(141, 5, 'Trousers', '#'),
(142, 5, 'Sweatshirts', '#'),
(143, 5, 'Product Layout', '#'),
(144, 5, 'Left sidebar', 'index.php?id_product=22&id_product_attribute=57&rewrite=hp-lp3065&controller=product&id_lang=1&sidebar=left'),
(145, 5, 'Right sidebar', 'index.php?id_product=22&id_product_attribute=57&rewrite=hp-lp3065&controller=product&id_lang=1&sidebar=right'),
(146, 5, 'No Sidebar', 'index.php?id_product=22&id_product_attribute=57&rewrite=hp-lp3065&controller=product&id_lang=1&sidebar=no'),
(147, 5, '3 Columns Layout', 'index.php?id_product=22&id_product_attribute=57&rewrite=hp-lp3065&controller=product&id_lang=1&sidebar=no&layout=product-layout-3columns'),
(148, 5, '2 Columns Layout', 'index.php?id_product=22&id_product_attribute=57&rewrite=hp-lp3065&controller=product&id_lang=1&sidebar=left'),
(151, 5, 'Product Type', '#'),
(152, 5, 'Virtual Product', ''),
(153, 5, 'Standard Product', ''),
(154, 5, 'Pack Products', ''),
(155, 5, 'Product Color Swatch', ''),
(156, 5, 'Product with custom tab', ''),
(157, 5, 'Product with video', ''),
(158, 5, 'Product out of stock', ''),
(159, 5, 'Add to cart', '#'),
(160, 5, 'Ajax Default', 'index.php?jpb_addtocart=default'),
(161, 5, 'Ajax + Preview Popup', 'index.php?jpb_addtocart=ajax_popup'),
(162, 5, 'Ajax + Image Moving', 'index.php?jpb_addtocart=ajax_moveimage'),
(163, 5, 'Ajax + Cart at Bottom', 'index.php?jpb_addtocart=ajax_cartbottom'),
(164, 5, 'Ajax + Cart at Sidebar', 'index.php?jpb_addtocart=ajax_cartsidebar'),
(165, 5, 'No Ajax', 'index.php?jpb_addtocart=no_ajax'),
(166, 5, 'Category Layout', '#'),
(167, 5, 'Left sidebar', 'index.php?id_category=10&controller=category&id_lang=1&sidebar=left'),
(168, 5, 'Right sidebar', 'index.php?id_category=10&controller=category&id_lang=1&sidebar=right'),
(169, 5, 'No Sidebar', 'index.php?id_category=10&controller=category&id_lang=1&sidebar=no'),
(170, 5, 'Category Banner', 'index.php?id_category=112&controller=category&id_lang=1&sidebar=left&layout=category-layout-banner'),
(171, 5, ' Banner and Descriptions', 'index.php?id_category=112&controller=category&id_lang=1&sidebar=left&layout=category-layout-bannerandesc'),
(172, 5, 'Category Descriptions', 'index.php?id_category=112&controller=category&id_lang=1&sidebar=left&layout=category-layout-desc'),
(173, 5, 'Grid 2 Colums', 'index.php?id_category=10&controller=category&id_lang=1&ppr=2'),
(174, 5, 'Grid 3 Colums', 'index.php?id_category=10&controller=category&id_lang=1&ppr=3'),
(175, 5, 'Grid 4 Colums', 'index.php?id_category=10&controller=category&id_lang=1&ppr=4'),
(176, 5, 'Grid 5 Colums', 'index.php?id_category=10&controller=category&id_lang=1&sidebar=no&ppr=5'),
(177, 5, 'Grid 6 Colums', 'index.php?id_category=10&controller=category&id_lang=1&sidebar=no&ppr=6'),
(178, 5, 'List Layout', 'index.php?id_category=10&controller=category&id_lang=1&jpb_grid=0&sidebar=left'),
(179, 5, 'Blog Category', ''),
(180, 5, 'Blog single post', ''),
(181, 5, 'Blog categories', ''),
(182, 5, 'Blog Tags', ''),
(183, 5, 'Blog Archives', ''),
(184, 5, 'Category - Left sidebar', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=left'),
(185, 5, 'Category - Right sidebar', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=right'),
(186, 5, 'Category - No sidebar', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no'),
(187, 5, '2 Columns', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no&layout=category-layout-2columns'),
(188, 5, '3 Columns', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no&layout=category-layout-3columns'),
(189, 5, '4 Columns', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no&layout=category-layout-4columns'),
(190, 5, 'Left sidebar', 'index.php?fc=module&module=jmsblog&category_slug=news&post_id=2&controller=post&id_lang=1&sidebar=left'),
(191, 5, 'Right sidebar', 'index.php?fc=module&module=jmsblog&category_slug=news&post_id=2&controller=post&id_lang=1&sidebar=right'),
(192, 5, 'No Sidebar', 'index.php?fc=module&module=jmsblog&category_slug=news&post_id=2&controller=post&id_lang=1&sidebar=no'),
(193, 5, 'Categories - Left sidebar', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=left'),
(194, 5, 'Categories - Right sidebar', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=right'),
(195, 5, 'Categories - No sidebar', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=no'),
(196, 5, '2 Columns', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=left'),
(197, 5, '3 Columns', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=no&layout=categories-layout-3columns'),
(198, 5, '4 Columns', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=no&layout=categories-layout-4columns'),
(200, 5, 'Bicycle Home', '#'),
(202, 5, 'Digital Home', '#'),
(204, 5, 'Fashion Home', '#'),
(206, 5, 'Food Home', '#'),
(207, 5, 'Furniture Home V.1', 'index.php?settingpanel=1&jpb_homepage=9'),
(209, 5, 'Furniture Home', '#'),
(210, 5, 'Furniture Home V.2', 'index.php?settingpanel=1&jpb_homepage=10'),
(212, 5, 'Jewellry Home', '#'),
(213, 5, 'Jewellry Home V.1', 'index.php?settingpanel=1&jpb_homepage=11'),
(214, 5, 'Jewellry Home V.2', 'index.php?settingpanel=1&jpb_homepage=12'),
(216, 5, 'Shoes Home V.1', 'index.php?settingpanel=1&jpb_homepage=13'),
(217, 5, 'Shoes Home', '#'),
(218, 5, 'Shoes Home V.2', 'index.php?settingpanel=1&jpb_homepage=14'),
(220, 5, 'Sunglass Home V.1', 'index.php?settingpanel=1&jpb_homepage=15'),
(221, 5, 'Sungglass Home', '#'),
(224, 5, 'Tools Home V.1', 'index.php?settingpanel=1&jpb_homepage=17'),
(225, 5, 'Tools Home', '#'),
(226, 5, 'Tools Home V.2', 'index.php?settingpanel=1&jpb_homepage=18'),
(228, 5, 'Watches Home V.1', 'index.php?settingpanel=1&jpb_homepage=19'),
(229, 5, 'Watches Home', '#'),
(230, 5, 'Watches Home V.2', 'index.php?settingpanel=1&jpb_homepage=20'),
(231, 5, 'Sunglass Home V.2', 'index.php?settingpanel=1&jpb_homepage=16'),
(232, 5, 'Accessories & supplies', ''),
(233, 5, 'Playstation 4 Consoles', ''),
(234, 5, '3D glasses', ''),
(235, 5, 'virtual reality headsets', ''),
(236, 5, 'PC Accessories', ''),
(241, 5, 'Jeans', ''),
(242, 5, 'Denim Jackets', ''),
(245, 5, 'Speakers ', ''),
(246, 5, 'Headsets ', ''),
(247, 5, 'Product Box Gutter', '#'),
(248, 5, 'No Gutter (0px)', 'index.php?id_category=10&controller=category&id_lang=1&jpb_gutterwidth=0&sidebar=left'),
(249, 5, 'Small Gutter (10px)', 'index.php?id_category=10&controller=category&id_lang=1&jpb_gutterwidth=10&sidebar=left'),
(250, 5, 'Medium Gutter (20px)', 'index.php?id_category=10&controller=category&id_lang=1&jpb_gutterwidth=20&sidebar=left'),
(251, 5, 'Gutter Default (30px)', 'index.php?id_category=10&controller=category&id_lang=1&sidebar=left'),
(252, 5, 'Large Gutter (40px)', 'index.php?id_category=10&controller=category&id_lang=1&jpb_gutterwidth=40&sidebar=left'),
(253, 5, 'Extra Large Gutter (60px)', 'index.php?id_category=10&controller=category&id_lang=1&jpb_gutterwidth=60&sidebar=no'),
(84, 7, 'Home', 'index.php'),
(85, 7, 'Shop', ''),
(86, 7, 'Products', ''),
(87, 7, 'Pages', ''),
(88, 7, 'Blog', ''),
(89, 7, 'Contact', 'index.php?controller=contact'),
(90, 7, 'Bicycle Home V.1', 'index.php?settingpanel=1&jpb_homepage=1'),
(91, 7, 'Bicycle Home V.2', 'index.php?settingpanel=1&jpb_homepage=2'),
(92, 7, 'Digital Home V.1', 'index.php?settingpanel=1&jpb_homepage=3'),
(93, 7, 'Digital Home V.2', 'index.php?settingpanel=1&jpb_homepage=4'),
(94, 7, 'Fashion Home V.1', 'index.php?settingpanel=1&jpb_homepage=5'),
(95, 7, 'Fashion Home V.2', 'index.php?settingpanel=1&jpb_homepage=6'),
(96, 7, 'Food  Home V.1', 'index.php?settingpanel=1&jpb_homepage=7'),
(97, 7, 'Food  Home V.2', 'index.php?settingpanel=1&jpb_homepage=8'),
(98, 7, 'Typography', ''),
(99, 7, 'Wishlist Page', 'index.php?fc=module&module=jmswishlist&controller=mywishlist&id_lang=1'),
(100, 7, 'Our Store', 'index.php?controller=stores'),
(101, 7, 'Search Page', 'index.php?controller=search&search_query=gop'),
(102, 7, 'Site Map', 'index.php?controller=sitemap'),
(103, 7, 'About Us', 'index.php?controller=new-products'),
(104, 7, 'Best Sales', 'index.php?controller=best-sales'),
(105, 7, '404 Page', 'index.php?controller=404'),
(111, 7, 'LG Image', ''),
(112, 7, 'audio & television', '#'),
(113, 7, '3D glasses', '#'),
(114, 7, 'virtual reality headsets', '#'),
(115, 7, 'PC Accessories', '#'),
(116, 7, 'Video Glasses', '#'),
(117, 7, 'PC game headsets', '#'),
(118, 7, 'video game VR headsets', '#'),
(119, 7, 'Accessories', '#'),
(120, 7, 'Shoes & Bags', '#'),
(121, 7, 'Sunglasses', '#'),
(122, 7, 'Watches & Jewelry', '#'),
(123, 7, 'Scarves & Gloves', '#'),
(124, 7, 'Hats & Ties', '#'),
(125, 7, 'Belts', '#'),
(126, 7, 'Sony Image', ''),
(127, 7, 'Samsung Image', ''),
(128, 7, 'Men', '#'),
(129, 7, 'Blazers', '#'),
(130, 7, 'Trousers', '#'),
(131, 7, 'T-Shirts', '#'),
(132, 7, 'Polo-Shirts', '#'),
(133, 7, 'Short', '#'),
(134, 7, 'Jeans', '#'),
(135, 7, 'Discount Image', ''),
(137, 7, 'Polo-Shirts', '#'),
(138, 7, 'Jeans', '#'),
(139, 7, 'Dresess', '#'),
(140, 7, 'Shorts', '#'),
(141, 7, 'Trousers', '#'),
(142, 7, 'Sweatshirts', '#'),
(143, 7, 'Product Layout', '#'),
(144, 7, 'Left sidebar', 'index.php?id_product=22&id_product_attribute=57&rewrite=hp-lp3065&controller=product&id_lang=1&sidebar=left'),
(145, 7, 'Right sidebar', 'index.php?id_product=22&id_product_attribute=57&rewrite=hp-lp3065&controller=product&id_lang=1&sidebar=right'),
(146, 7, 'No Sidebar', 'index.php?id_product=22&id_product_attribute=57&rewrite=hp-lp3065&controller=product&id_lang=1&sidebar=no'),
(147, 7, '3 Columns Layout', 'index.php?id_product=22&id_product_attribute=57&rewrite=hp-lp3065&controller=product&id_lang=1&sidebar=no&layout=product-layout-3columns'),
(148, 7, '2 Columns Layout', 'index.php?id_product=22&id_product_attribute=57&rewrite=hp-lp3065&controller=product&id_lang=1&sidebar=left'),
(151, 7, 'Product Type', '#'),
(152, 7, 'Virtual Product', ''),
(153, 7, 'Standard Product', ''),
(154, 7, 'Pack Products', ''),
(155, 7, 'Product Color Swatch', ''),
(156, 7, 'Product with custom tab', ''),
(157, 7, 'Product with video', ''),
(158, 7, 'Product out of stock', ''),
(159, 7, 'Add to cart', '#'),
(160, 7, 'Ajax Default', 'index.php?jpb_addtocart=default'),
(161, 7, 'Ajax + Preview Popup', 'index.php?jpb_addtocart=ajax_popup'),
(162, 7, 'Ajax + Image Moving', 'index.php?jpb_addtocart=ajax_moveimage'),
(163, 7, 'Ajax + Cart at Bottom', 'index.php?jpb_addtocart=ajax_cartbottom'),
(164, 7, 'Ajax + Cart at Sidebar', 'index.php?jpb_addtocart=ajax_cartsidebar'),
(165, 7, 'No Ajax', 'index.php?jpb_addtocart=no_ajax'),
(166, 7, 'Category Layout', '#'),
(167, 7, 'Left sidebar', 'index.php?id_category=10&controller=category&id_lang=1&sidebar=left'),
(168, 7, 'Right sidebar', 'index.php?id_category=10&controller=category&id_lang=1&sidebar=right'),
(169, 7, 'No Sidebar', 'index.php?id_category=10&controller=category&id_lang=1&sidebar=no'),
(170, 7, 'Category Banner', 'index.php?id_category=112&controller=category&id_lang=1&sidebar=left&layout=category-layout-banner'),
(171, 7, ' Banner and Descriptions', 'index.php?id_category=112&controller=category&id_lang=1&sidebar=left&layout=category-layout-bannerandesc'),
(172, 7, 'Category Descriptions', 'index.php?id_category=112&controller=category&id_lang=1&sidebar=left&layout=category-layout-desc'),
(173, 7, 'Grid 2 Colums', 'index.php?id_category=10&controller=category&id_lang=1&ppr=2'),
(174, 7, 'Grid 3 Colums', 'index.php?id_category=10&controller=category&id_lang=1&ppr=3'),
(175, 7, 'Grid 4 Colums', 'index.php?id_category=10&controller=category&id_lang=1&ppr=4'),
(176, 7, 'Grid 5 Colums', 'index.php?id_category=10&controller=category&id_lang=1&sidebar=no&ppr=5'),
(177, 7, 'Grid 6 Colums', 'index.php?id_category=10&controller=category&id_lang=1&sidebar=no&ppr=6'),
(178, 7, 'List Layout', 'index.php?id_category=10&controller=category&id_lang=1&jpb_grid=0&sidebar=left'),
(179, 7, 'Blog Category', ''),
(180, 7, 'Blog single post', ''),
(181, 7, 'Blog categories', ''),
(182, 7, 'Blog Tags', ''),
(183, 7, 'Blog Archives', ''),
(184, 7, 'Category - Left sidebar', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=left'),
(185, 7, 'Category - Right sidebar', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=right'),
(186, 7, 'Category - No sidebar', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no'),
(187, 7, '2 Columns', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no&layout=category-layout-2columns'),
(188, 7, '3 Columns', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no&layout=category-layout-3columns'),
(189, 7, '4 Columns', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no&layout=category-layout-4columns'),
(190, 7, 'Left sidebar', 'index.php?fc=module&module=jmsblog&category_slug=news&post_id=2&controller=post&id_lang=1&sidebar=left'),
(191, 7, 'Right sidebar', 'index.php?fc=module&module=jmsblog&category_slug=news&post_id=2&controller=post&id_lang=1&sidebar=right'),
(192, 7, 'No Sidebar', 'index.php?fc=module&module=jmsblog&category_slug=news&post_id=2&controller=post&id_lang=1&sidebar=no'),
(193, 7, 'Categories - Left sidebar', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=left'),
(194, 7, 'Categories - Right sidebar', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=right'),
(195, 7, 'Categories - No sidebar', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=no'),
(196, 7, '2 Columns', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=left'),
(197, 7, '3 Columns', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=no&layout=categories-layout-3columns'),
(198, 7, '4 Columns', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=no&layout=categories-layout-4columns'),
(200, 7, 'Bicycle Home', '#'),
(202, 7, 'Digital Home', '#'),
(204, 7, 'Fashion Home', '#'),
(206, 7, 'Food Home', '#'),
(207, 7, 'Furniture Home V.1', 'index.php?settingpanel=1&jpb_homepage=9'),
(209, 7, 'Furniture Home', '#'),
(210, 7, 'Furniture Home V.2', 'index.php?settingpanel=1&jpb_homepage=10'),
(212, 7, 'Jewellry Home', '#'),
(213, 7, 'Jewellry Home V.1', 'index.php?settingpanel=1&jpb_homepage=11'),
(214, 7, 'Jewellry Home V.2', 'index.php?settingpanel=1&jpb_homepage=12'),
(216, 7, 'Shoes Home V.1', 'index.php?settingpanel=1&jpb_homepage=13'),
(217, 7, 'Shoes Home', '#'),
(218, 7, 'Shoes Home V.2', 'index.php?settingpanel=1&jpb_homepage=14'),
(220, 7, 'Sunglass Home V.1', 'index.php?settingpanel=1&jpb_homepage=15'),
(221, 7, 'Sungglass Home', '#'),
(224, 7, 'Tools Home V.1', 'index.php?settingpanel=1&jpb_homepage=17'),
(225, 7, 'Tools Home', '#'),
(226, 7, 'Tools Home V.2', 'index.php?settingpanel=1&jpb_homepage=18'),
(228, 7, 'Watches Home V.1', 'index.php?settingpanel=1&jpb_homepage=19'),
(229, 7, 'Watches Home', '#'),
(230, 7, 'Watches Home V.2', 'index.php?settingpanel=1&jpb_homepage=20'),
(231, 7, 'Sunglass Home V.2', 'index.php?settingpanel=1&jpb_homepage=16'),
(232, 7, 'Accessories & supplies', ''),
(233, 7, 'Playstation 4 Consoles', ''),
(234, 7, '3D glasses', ''),
(235, 7, 'virtual reality headsets', ''),
(236, 7, 'PC Accessories', ''),
(241, 7, 'Jeans', ''),
(242, 7, 'Denim Jackets', ''),
(245, 7, 'Speakers ', ''),
(246, 7, 'Headsets ', ''),
(247, 7, 'Product Box Gutter', '#'),
(248, 7, 'No Gutter (0px)', 'index.php?id_category=10&controller=category&id_lang=1&jpb_gutterwidth=0&sidebar=left'),
(249, 7, 'Small Gutter (10px)', 'index.php?id_category=10&controller=category&id_lang=1&jpb_gutterwidth=10&sidebar=left'),
(250, 7, 'Medium Gutter (20px)', 'index.php?id_category=10&controller=category&id_lang=1&jpb_gutterwidth=20&sidebar=left'),
(251, 7, 'Gutter Default (30px)', 'index.php?id_category=10&controller=category&id_lang=1&sidebar=left'),
(252, 7, 'Large Gutter (40px)', 'index.php?id_category=10&controller=category&id_lang=1&jpb_gutterwidth=40&sidebar=left'),
(253, 7, 'Extra Large Gutter (60px)', 'index.php?id_category=10&controller=category&id_lang=1&jpb_gutterwidth=60&sidebar=no');

ALTER TABLE `_DB_PREFIX_jmsmegamenu`
  ADD PRIMARY KEY (`mitem_id`);

ALTER TABLE `_DB_PREFIX_jmsmegamenu`
  MODIFY `mitem_id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=254;

";
